// Code generated by partner-api-contract/tools/server-sdk/go.mjs. DO NOT EDIT.
package january

import "encoding/json"

// ActivityLevel accepts unknown future response enum values.
type ActivityLevel = string

const (
	ActivityLevelSedentary        ActivityLevel = "sedentary"
	ActivityLevelLightlyActive    ActivityLevel = "lightly_active"
	ActivityLevelModeratelyActive ActivityLevel = "moderately_active"
	ActivityLevelVeryActive       ActivityLevel = "very_active"
)

// AlternativeFood is generated from the January contract.
type AlternativeFood struct {
	ID        Optional[FoodID]               `json:"id"`
	Name      string                         `json:"name"`
	BrandName Optional[string]               `json:"brand_name"`
	Nutrients CompleteScanNutritionFacts     `json:"nutrients"`
	Servings  Optional[[]AlternativeServing] `json:"servings"`
}

func (v AlternativeFood) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	putOptional(m, "id", v.ID)
	m["name"] = v.Name
	putOptional(m, "brand_name", v.BrandName)
	m["nutrients"] = v.Nutrients
	putOptional(m, "servings", v.Servings)
	return json.Marshal(m)
}
func (v AlternativeFood) String() string   { return "january.AlternativeFood{[REDACTED]}" }
func (v AlternativeFood) GoString() string { return v.String() }

// AlternativeServing is generated from the January contract.
type AlternativeServing struct {
	ID       ServingID         `json:"id"`
	Quantity Optional[float64] `json:"quantity"`
	Unit     string            `json:"unit"`
}

func (v AlternativeServing) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["id"] = v.ID
	putOptional(m, "quantity", v.Quantity)
	m["unit"] = v.Unit
	return json.Marshal(m)
}
func (v AlternativeServing) String() string   { return "january.AlternativeServing{[REDACTED]}" }
func (v AlternativeServing) GoString() string { return v.String() }

// APIErrorDto is generated from the January contract.
type APIErrorDto struct {
	Message string `json:"message"`
	Code    string `json:"code"`
	DocsURL string `json:"docs_url"`
}

func (v APIErrorDto) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["message"] = v.Message
	m["code"] = v.Code
	m["docs_url"] = v.DocsURL
	return json.Marshal(m)
}
func (v APIErrorDto) String() string   { return "january.APIErrorDto{[REDACTED]}" }
func (v APIErrorDto) GoString() string { return v.String() }

// AutocompleteFoodCategory accepts unknown future response enum values.
type AutocompleteFoodCategory = string

const (
	AutocompleteFoodCategoryGeneral AutocompleteFoodCategory = "general"
	AutocompleteFoodCategoryBranded AutocompleteFoodCategory = "branded"
)

// AutocompleteFoodsRequest is generated from the January contract.
type AutocompleteFoodsRequest struct {
	EndUserID string                             `json:"x-end-user-id,omitempty"`
	Query     string                             `json:"query"`
	Category  Optional[AutocompleteFoodCategory] `json:"category"`
	Limit     Optional[float64]                  `json:"limit"`
}

func (v AutocompleteFoodsRequest) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	if v.EndUserID != "" {
		m["x-end-user-id"] = v.EndUserID
	}
	m["query"] = v.Query
	putOptional(m, "category", v.Category)
	putOptional(m, "limit", v.Limit)
	return json.Marshal(m)
}
func (v AutocompleteFoodsRequest) String() string {
	return "january.AutocompleteFoodsRequest{[REDACTED]}"
}
func (v AutocompleteFoodsRequest) GoString() string { return v.String() }

// AutocompleteFoodsResponse is generated from the January contract.
type AutocompleteFoodsResponse struct {
	Items []FoodSuggestion `json:"items"`
}

func (v AutocompleteFoodsResponse) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["items"] = v.Items
	return json.Marshal(m)
}
func (v AutocompleteFoodsResponse) String() string {
	return "january.AutocompleteFoodsResponse{[REDACTED]}"
}
func (v AutocompleteFoodsResponse) GoString() string { return v.String() }

// Barcode accepts unknown future response enum values.
type Barcode = string

// CGMReading is generated from the January contract.
type CGMReading struct {
	Timestamp string  `json:"timestamp"`
	Value     float64 `json:"value"`
}

func (v CGMReading) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["timestamp"] = v.Timestamp
	m["value"] = v.Value
	return json.Marshal(m)
}
func (v CGMReading) String() string   { return "january.CGMReading{[REDACTED]}" }
func (v CGMReading) GoString() string { return v.String() }

// ClientTokenResponseDto is generated from the January contract.
type ClientTokenResponseDto struct {
	Token     string   `json:"token"`
	ExpiresIn float64  `json:"expires_in"`
	ExpiresAt string   `json:"expires_at"`
	EndUserID string   `json:"end_user_id"`
	Scopes    []string `json:"scopes"`
}

func (v ClientTokenResponseDto) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["token"] = v.Token
	m["expires_in"] = v.ExpiresIn
	m["expires_at"] = v.ExpiresAt
	m["end_user_id"] = v.EndUserID
	m["scopes"] = v.Scopes
	return json.Marshal(m)
}
func (v ClientTokenResponseDto) String() string   { return "january.ClientTokenResponseDto{[REDACTED]}" }
func (v ClientTokenResponseDto) GoString() string { return v.String() }

// CompleteScanNutritionFacts is generated from the January contract.
type CompleteScanNutritionFacts struct {
	Calories         Optional[NutrientAmount] `json:"calories"`
	Protein          Optional[NutrientAmount] `json:"protein"`
	Carbohydrates    Optional[NutrientAmount] `json:"carbohydrates"`
	NetCarbohydrates Optional[NutrientAmount] `json:"net_carbohydrates"`
	TotalFat         Optional[NutrientAmount] `json:"total_fat"`
	SaturatedFat     Optional[NutrientAmount] `json:"saturated_fat"`
	Fiber            Optional[NutrientAmount] `json:"fiber"`
	TotalSugars      Optional[NutrientAmount] `json:"total_sugars"`
	AddedSugars      Optional[NutrientAmount] `json:"added_sugars"`
	Sodium           Optional[NutrientAmount] `json:"sodium"`
}

func (v CompleteScanNutritionFacts) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	putOptional(m, "calories", v.Calories)
	putOptional(m, "protein", v.Protein)
	putOptional(m, "carbohydrates", v.Carbohydrates)
	putOptional(m, "net_carbohydrates", v.NetCarbohydrates)
	putOptional(m, "total_fat", v.TotalFat)
	putOptional(m, "saturated_fat", v.SaturatedFat)
	putOptional(m, "fiber", v.Fiber)
	putOptional(m, "total_sugars", v.TotalSugars)
	putOptional(m, "added_sugars", v.AddedSugars)
	putOptional(m, "sodium", v.Sodium)
	return json.Marshal(m)
}
func (v CompleteScanNutritionFacts) String() string {
	return "january.CompleteScanNutritionFacts{[REDACTED]}"
}
func (v CompleteScanNutritionFacts) GoString() string { return v.String() }

// ConfidenceScore accepts unknown future response enum values.
type ConfidenceScore = string

const (
	ConfidenceScoreHigh   ConfidenceScore = "high"
	ConfidenceScoreMedium ConfidenceScore = "medium"
	ConfidenceScoreLow    ConfidenceScore = "low"
)

// ConsumedHistoricalFood is generated from the January contract.
type ConsumedHistoricalFood struct {
	Timestamp string              `json:"timestamp"`
	ID        FoodID              `json:"id"`
	Serving   FoodLogInputServing `json:"serving"`
}

func (v ConsumedHistoricalFood) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["timestamp"] = v.Timestamp
	m["id"] = v.ID
	m["serving"] = v.Serving
	return json.Marshal(m)
}
func (v ConsumedHistoricalFood) String() string   { return "january.ConsumedHistoricalFood{[REDACTED]}" }
func (v ConsumedHistoricalFood) GoString() string { return v.String() }

// CorrectPhotoScanBody is generated from the January contract.
type CorrectPhotoScanBody struct {
	MealName   Optional[string] `json:"meal_name"`
	Detections []FoodDetection  `json:"detections"`
	UserInput  string           `json:"user_input"`
}

func (v CorrectPhotoScanBody) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	putOptional(m, "meal_name", v.MealName)
	m["detections"] = v.Detections
	m["user_input"] = v.UserInput
	return json.Marshal(m)
}
func (v CorrectPhotoScanBody) String() string   { return "january.CorrectPhotoScanBody{[REDACTED]}" }
func (v CorrectPhotoScanBody) GoString() string { return v.String() }

// CorrectPhotoScanRequest is generated from the January contract.
type CorrectPhotoScanRequest struct {
	EndUserID  string           `json:"x-end-user-id,omitempty"`
	MealName   Optional[string] `json:"meal_name"`
	Detections []FoodDetection  `json:"detections"`
	UserInput  string           `json:"user_input"`
}

func (v CorrectPhotoScanRequest) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	if v.EndUserID != "" {
		m["x-end-user-id"] = v.EndUserID
	}
	putOptional(m, "meal_name", v.MealName)
	m["detections"] = v.Detections
	m["user_input"] = v.UserInput
	return json.Marshal(m)
}
func (v CorrectPhotoScanRequest) String() string {
	return "january.CorrectPhotoScanRequest{[REDACTED]}"
}
func (v CorrectPhotoScanRequest) GoString() string { return v.String() }

// CreateClientTokenDto is generated from the January contract.
type CreateClientTokenDto struct {
	EndUserID  string             `json:"end_user_id"`
	Scopes     Optional[[]string] `json:"scopes"`
	TTLSeconds Optional[float64]  `json:"ttl_seconds"`
}

func (v CreateClientTokenDto) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["end_user_id"] = v.EndUserID
	putOptional(m, "scopes", v.Scopes)
	putOptional(m, "ttl_seconds", v.TTLSeconds)
	return json.Marshal(m)
}
func (v CreateClientTokenDto) String() string   { return "january.CreateClientTokenDto{[REDACTED]}" }
func (v CreateClientTokenDto) GoString() string { return v.String() }

// CreateFoodLogBody is generated from the January contract.
type CreateFoodLogBody struct {
	Foods        []FoodLogInputFood `json:"foods"`
	TimestampUTC Optional[string]   `json:"timestamp_utc"`
	Name         Optional[string]   `json:"name"`
}

func (v CreateFoodLogBody) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["foods"] = v.Foods
	putOptional(m, "timestamp_utc", v.TimestampUTC)
	putOptional(m, "name", v.Name)
	return json.Marshal(m)
}
func (v CreateFoodLogBody) String() string   { return "january.CreateFoodLogBody{[REDACTED]}" }
func (v CreateFoodLogBody) GoString() string { return v.String() }

// CreateFoodLogRequest is generated from the January contract.
type CreateFoodLogRequest struct {
	EndUserID       string             `json:"x-end-user-id,omitempty"`
	EndUserTimezone string             `json:"x-end-user-timezone,omitempty"`
	Foods           []FoodLogInputFood `json:"foods"`
	TimestampUTC    Optional[string]   `json:"timestamp_utc"`
	Name            Optional[string]   `json:"name"`
}

func (v CreateFoodLogRequest) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	if v.EndUserID != "" {
		m["x-end-user-id"] = v.EndUserID
	}
	if v.EndUserTimezone != "" {
		m["x-end-user-timezone"] = v.EndUserTimezone
	}
	m["foods"] = v.Foods
	putOptional(m, "timestamp_utc", v.TimestampUTC)
	putOptional(m, "name", v.Name)
	return json.Marshal(m)
}
func (v CreateFoodLogRequest) String() string   { return "january.CreateFoodLogRequest{[REDACTED]}" }
func (v CreateFoodLogRequest) GoString() string { return v.String() }

// CreditsRequest is generated from the January contract.
type CreditsRequest struct {
	EndUserID string `json:"x-end-user-id,omitempty"`
}

func (v CreditsRequest) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	if v.EndUserID != "" {
		m["x-end-user-id"] = v.EndUserID
	}
	return json.Marshal(m)
}
func (v CreditsRequest) String() string   { return "january.CreditsRequest{[REDACTED]}" }
func (v CreditsRequest) GoString() string { return v.String() }

// CreditsResponseDto is generated from the January contract.
type CreditsResponseDto struct {
	Plan             string            `json:"plan"`
	PeriodStart      string            `json:"period_start"`
	PeriodEnd        string            `json:"period_end"`
	ResetsAt         string            `json:"resets_at"`
	IncludedCredits  Optional[float64] `json:"included_credits"`
	UsedCredits      float64           `json:"used_credits"`
	RemainingCredits Optional[float64] `json:"remaining_credits"`
}

func (v CreditsResponseDto) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["plan"] = v.Plan
	m["period_start"] = v.PeriodStart
	m["period_end"] = v.PeriodEnd
	m["resets_at"] = v.ResetsAt
	putOptional(m, "included_credits", v.IncludedCredits)
	m["used_credits"] = v.UsedCredits
	putOptional(m, "remaining_credits", v.RemainingCredits)
	return json.Marshal(m)
}
func (v CreditsResponseDto) String() string   { return "january.CreditsResponseDto{[REDACTED]}" }
func (v CreditsResponseDto) GoString() string { return v.String() }

// DeleteFoodLogRequest is generated from the January contract.
type DeleteFoodLogRequest struct {
	EndUserID       string    `json:"x-end-user-id,omitempty"`
	EndUserTimezone string    `json:"x-end-user-timezone,omitempty"`
	LogID           FoodLogID `json:"log_id"`
}

func (v DeleteFoodLogRequest) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	if v.EndUserID != "" {
		m["x-end-user-id"] = v.EndUserID
	}
	if v.EndUserTimezone != "" {
		m["x-end-user-timezone"] = v.EndUserTimezone
	}
	m["log_id"] = v.LogID
	return json.Marshal(m)
}
func (v DeleteFoodLogRequest) String() string   { return "january.DeleteFoodLogRequest{[REDACTED]}" }
func (v DeleteFoodLogRequest) GoString() string { return v.String() }

// DeleteFoodLogResponse is generated from the January contract.
type DeleteFoodLogResponse struct {
	Status string `json:"status"`
}

func (v DeleteFoodLogResponse) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["status"] = v.Status
	return json.Marshal(m)
}
func (v DeleteFoodLogResponse) String() string   { return "january.DeleteFoodLogResponse{[REDACTED]}" }
func (v DeleteFoodLogResponse) GoString() string { return v.String() }

// DetectedFood is generated from the January contract.
type DetectedFood struct {
	ID        Optional[FoodID]           `json:"id"`
	Name      string                     `json:"name"`
	BrandName Optional[string]           `json:"brand_name"`
	Nutrients CompleteScanNutritionFacts `json:"nutrients"`
	Servings  []DetectedServing          `json:"servings"`
}

func (v DetectedFood) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	putOptional(m, "id", v.ID)
	m["name"] = v.Name
	putOptional(m, "brand_name", v.BrandName)
	m["nutrients"] = v.Nutrients
	m["servings"] = v.Servings
	return json.Marshal(m)
}
func (v DetectedFood) String() string   { return "january.DetectedFood{[REDACTED]}" }
func (v DetectedFood) GoString() string { return v.String() }

// DetectedServing is generated from the January contract.
type DetectedServing struct {
	ID               ServingID         `json:"id"`
	Quantity         Optional[float64] `json:"quantity"`
	Unit             string            `json:"unit"`
	SelectedQuantity Optional[float64] `json:"selected_quantity"`
}

func (v DetectedServing) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["id"] = v.ID
	putOptional(m, "quantity", v.Quantity)
	m["unit"] = v.Unit
	putOptional(m, "selected_quantity", v.SelectedQuantity)
	return json.Marshal(m)
}
func (v DetectedServing) String() string   { return "january.DetectedServing{[REDACTED]}" }
func (v DetectedServing) GoString() string { return v.String() }

// DietPreference accepts unknown future response enum values.
type DietPreference = string

const (
	DietPreferenceVegetarian      DietPreference = "vegetarian"
	DietPreferenceVegan           DietPreference = "vegan"
	DietPreferenceKeto            DietPreference = "keto"
	DietPreferencePaleo           DietPreference = "paleo"
	DietPreferencePescatarian     DietPreference = "pescatarian"
	DietPreferenceLowCarbohydrate DietPreference = "low_carbohydrate"
	DietPreferenceHighProtein     DietPreference = "high_protein"
	DietPreferenceKosher          DietPreference = "kosher"
	DietPreferenceHalal           DietPreference = "halal"
)

// DietRestriction accepts unknown future response enum values.
type DietRestriction = string

const (
	DietRestrictionGluten    DietRestriction = "gluten"
	DietRestrictionLactose   DietRestriction = "lactose"
	DietRestrictionYeast     DietRestriction = "yeast"
	DietRestrictionTreeNuts  DietRestriction = "tree_nuts"
	DietRestrictionPeanuts   DietRestriction = "peanuts"
	DietRestrictionDairy     DietRestriction = "dairy"
	DietRestrictionEggs      DietRestriction = "eggs"
	DietRestrictionSulfites  DietRestriction = "sulfites"
	DietRestrictionSoy       DietRestriction = "soy"
	DietRestrictionWheat     DietRestriction = "wheat"
	DietRestrictionShellfish DietRestriction = "shellfish"
	DietRestrictionFish      DietRestriction = "fish"
	DietRestrictionMushrooms DietRestriction = "mushrooms"
	DietRestrictionSesame    DietRestriction = "sesame"
	DietRestrictionMsg       DietRestriction = "msg"
	DietRestrictionCaffeine  DietRestriction = "caffeine"
	DietRestrictionFodmaps   DietRestriction = "fodmaps"
)

// ErrorResponse is generated from the January contract.
type ErrorResponse struct {
	Message string `json:"message"`
	Code    string `json:"code"`
	DocsURL string `json:"docs_url"`
}

func (v ErrorResponse) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["message"] = v.Message
	m["code"] = v.Code
	m["docs_url"] = v.DocsURL
	return json.Marshal(m)
}
func (v ErrorResponse) String() string   { return "january.ErrorResponse{[REDACTED]}" }
func (v ErrorResponse) GoString() string { return v.String() }

// FoodAlternative is generated from the January contract.
type FoodAlternative struct {
	Food AlternativeFood `json:"food"`
}

func (v FoodAlternative) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["food"] = v.Food
	return json.Marshal(m)
}
func (v FoodAlternative) String() string   { return "january.FoodAlternative{[REDACTED]}" }
func (v FoodAlternative) GoString() string { return v.String() }

// FoodCategory accepts unknown future response enum values.
type FoodCategory = string

const (
	FoodCategoryGeneral FoodCategory = "general"
	FoodCategoryBranded FoodCategory = "branded"
	FoodCategoryRecipe  FoodCategory = "recipe"
)

// FoodDetection is generated from the January contract.
type FoodDetection struct {
	ConfidenceScore Optional[ConfidenceScore] `json:"confidence_score"`
	Food            DetectedFood              `json:"food"`
}

func (v FoodDetection) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	putOptional(m, "confidence_score", v.ConfidenceScore)
	m["food"] = v.Food
	return json.Marshal(m)
}
func (v FoodDetection) String() string   { return "january.FoodDetection{[REDACTED]}" }
func (v FoodDetection) GoString() string { return v.String() }

// FoodID accepts unknown future response enum values.
type FoodID = int64

// FoodLog is generated from the January contract.
type FoodLog struct {
	ID           FoodLogID        `json:"id"`
	Foods        []LoggedFood     `json:"foods"`
	TimestampUTC string           `json:"timestamp_utc"`
	Name         Optional[string] `json:"name"`
}

func (v FoodLog) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["id"] = v.ID
	m["foods"] = v.Foods
	m["timestamp_utc"] = v.TimestampUTC
	putOptional(m, "name", v.Name)
	return json.Marshal(m)
}
func (v FoodLog) String() string   { return "january.FoodLog{[REDACTED]}" }
func (v FoodLog) GoString() string { return v.String() }

// FoodLogID accepts unknown future response enum values.
type FoodLogID = string

// FoodLogInputFood is generated from the January contract.
type FoodLogInputFood struct {
	ID      FoodID              `json:"id"`
	Serving FoodLogInputServing `json:"serving"`
}

func (v FoodLogInputFood) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["id"] = v.ID
	m["serving"] = v.Serving
	return json.Marshal(m)
}
func (v FoodLogInputFood) String() string   { return "january.FoodLogInputFood{[REDACTED]}" }
func (v FoodLogInputFood) GoString() string { return v.String() }

// FoodLogInputServing is generated from the January contract.
type FoodLogInputServing struct {
	ID       ServingID `json:"id"`
	Quantity float64   `json:"quantity"`
}

func (v FoodLogInputServing) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["id"] = v.ID
	m["quantity"] = v.Quantity
	return json.Marshal(m)
}
func (v FoodLogInputServing) String() string   { return "january.FoodLogInputServing{[REDACTED]}" }
func (v FoodLogInputServing) GoString() string { return v.String() }

// FoodScan is generated from the January contract.
type FoodScan struct {
	MealName       Optional[string]                     `json:"meal_name"`
	TotalNutrients Optional[CompleteScanNutritionFacts] `json:"total_nutrients"`
	Detections     []FoodDetection                      `json:"detections"`
}

func (v FoodScan) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	putOptional(m, "meal_name", v.MealName)
	putOptional(m, "total_nutrients", v.TotalNutrients)
	m["detections"] = v.Detections
	return json.Marshal(m)
}
func (v FoodScan) String() string   { return "january.FoodScan{[REDACTED]}" }
func (v FoodScan) GoString() string { return v.String() }

// FoodSearchItem is generated from the January contract.
type FoodSearchItem struct {
	ID            FoodID            `json:"id"`
	Name          string            `json:"name"`
	BrandName     Optional[string]  `json:"brand_name"`
	Nutrients     NutritionFacts    `json:"nutrients"`
	GlycemicIndex Optional[float64] `json:"glycemic_index"`
	GlycemicLoad  Optional[float64] `json:"glycemic_load"`
	ImageURL      Optional[string]  `json:"image_url"`
	UPC           Optional[string]  `json:"upc"`
	Servings      []ServingOption   `json:"servings"`
}

func (v FoodSearchItem) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["id"] = v.ID
	m["name"] = v.Name
	putOptional(m, "brand_name", v.BrandName)
	m["nutrients"] = v.Nutrients
	putOptional(m, "glycemic_index", v.GlycemicIndex)
	putOptional(m, "glycemic_load", v.GlycemicLoad)
	putOptional(m, "image_url", v.ImageURL)
	putOptional(m, "upc", v.UPC)
	m["servings"] = v.Servings
	return json.Marshal(m)
}
func (v FoodSearchItem) String() string   { return "january.FoodSearchItem{[REDACTED]}" }
func (v FoodSearchItem) GoString() string { return v.String() }

// FoodSearchResults is generated from the January contract.
type FoodSearchResults struct {
	TotalCount float64          `json:"total_count"`
	Items      []FoodSearchItem `json:"items"`
}

func (v FoodSearchResults) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["total_count"] = v.TotalCount
	m["items"] = v.Items
	return json.Marshal(m)
}
func (v FoodSearchResults) String() string   { return "january.FoodSearchResults{[REDACTED]}" }
func (v FoodSearchResults) GoString() string { return v.String() }

// FoodSuggestion is generated from the January contract.
type FoodSuggestion struct {
	ID        FoodID                   `json:"id"`
	Name      string                   `json:"name"`
	BrandName Optional[string]         `json:"brand_name"`
	ImageURL  Optional[string]         `json:"image_url"`
	Nutrients Optional[NutritionFacts] `json:"nutrients"`
}

func (v FoodSuggestion) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["id"] = v.ID
	m["name"] = v.Name
	putOptional(m, "brand_name", v.BrandName)
	putOptional(m, "image_url", v.ImageURL)
	putOptional(m, "nutrients", v.Nutrients)
	return json.Marshal(m)
}
func (v FoodSuggestion) String() string   { return "january.FoodSuggestion{[REDACTED]}" }
func (v FoodSuggestion) GoString() string { return v.String() }

// GetFoodRequest is generated from the January contract.
type GetFoodRequest struct {
	EndUserID string `json:"x-end-user-id,omitempty"`
	FoodID    FoodID `json:"food_id"`
}

func (v GetFoodRequest) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	if v.EndUserID != "" {
		m["x-end-user-id"] = v.EndUserID
	}
	m["food_id"] = v.FoodID
	return json.Marshal(m)
}
func (v GetFoodRequest) String() string   { return "january.GetFoodRequest{[REDACTED]}" }
func (v GetFoodRequest) GoString() string { return v.String() }

// GlucoseChart is generated from the January contract.
type GlucoseChart struct {
	Min float64 `json:"min"`
	Max float64 `json:"max"`
}

func (v GlucoseChart) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["min"] = v.Min
	m["max"] = v.Max
	return json.Marshal(m)
}
func (v GlucoseChart) String() string   { return "january.GlucoseChart{[REDACTED]}" }
func (v GlucoseChart) GoString() string { return v.String() }

// GlucoseImpact accepts unknown future response enum values.
type GlucoseImpact = string

const (
	GlucoseImpactLow    GlucoseImpact = "low"
	GlucoseImpactMedium GlucoseImpact = "medium"
	GlucoseImpactHigh   GlucoseImpact = "high"
)

// GlucosePrediction is generated from the January contract.
type GlucosePrediction struct {
	Prediction  []GlucosePredictionPoint `json:"prediction"`
	ImpactScore GlucoseImpact            `json:"impact_score"`
	Chart       GlucoseChart             `json:"chart"`
}

func (v GlucosePrediction) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["prediction"] = v.Prediction
	m["impact_score"] = v.ImpactScore
	m["chart"] = v.Chart
	return json.Marshal(m)
}
func (v GlucosePrediction) String() string   { return "january.GlucosePrediction{[REDACTED]}" }
func (v GlucosePrediction) GoString() string { return v.String() }

// GlucosePredictionPoint is generated from the January contract.
type GlucosePredictionPoint struct {
	Minutes float64 `json:"minutes"`
	Value   float64 `json:"value"`
}

func (v GlucosePredictionPoint) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["minutes"] = v.Minutes
	m["value"] = v.Value
	return json.Marshal(m)
}
func (v GlucosePredictionPoint) String() string   { return "january.GlucosePredictionPoint{[REDACTED]}" }
func (v GlucosePredictionPoint) GoString() string { return v.String() }

// GlucosePredictionProfile is generated from the January contract.
type GlucosePredictionProfile struct {
	Age              float64                      `json:"age"`
	Sex              Sex                          `json:"sex"`
	Height           Height                       `json:"height"`
	Weight           Weight                       `json:"weight"`
	ActivityLevel    Optional[ActivityLevel]      `json:"activity_level"`
	HealthConditions Optional[[]MedicalCondition] `json:"health_conditions"`
}

func (v GlucosePredictionProfile) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["age"] = v.Age
	m["sex"] = v.Sex
	m["height"] = v.Height
	m["weight"] = v.Weight
	putOptional(m, "activity_level", v.ActivityLevel)
	putOptional(m, "health_conditions", v.HealthConditions)
	return json.Marshal(m)
}
func (v GlucosePredictionProfile) String() string {
	return "january.GlucosePredictionProfile{[REDACTED]}"
}
func (v GlucosePredictionProfile) GoString() string { return v.String() }

// Height is generated from the January contract.
type Height struct {
	Value float64    `json:"value"`
	Unit  HeightUnit `json:"unit"`
}

func (v Height) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["value"] = v.Value
	m["unit"] = v.Unit
	return json.Marshal(m)
}
func (v Height) String() string   { return "january.Height{[REDACTED]}" }
func (v Height) GoString() string { return v.String() }

// HeightUnit accepts unknown future response enum values.
type HeightUnit = string

const (
	HeightUnitIn HeightUnit = "in"
	HeightUnitCm HeightUnit = "cm"
)

// ListFoodLogsRequest is generated from the January contract.
type ListFoodLogsRequest struct {
	EndUserID       string `json:"x-end-user-id,omitempty"`
	EndUserTimezone string `json:"x-end-user-timezone,omitempty"`
	Start           string `json:"start"`
	End             string `json:"end"`
}

func (v ListFoodLogsRequest) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	if v.EndUserID != "" {
		m["x-end-user-id"] = v.EndUserID
	}
	if v.EndUserTimezone != "" {
		m["x-end-user-timezone"] = v.EndUserTimezone
	}
	m["start"] = v.Start
	m["end"] = v.End
	return json.Marshal(m)
}
func (v ListFoodLogsRequest) String() string   { return "january.ListFoodLogsRequest{[REDACTED]}" }
func (v ListFoodLogsRequest) GoString() string { return v.String() }

// ListFoodLogsResponse is generated from the January contract.
type ListFoodLogsResponse struct {
	TotalCount float64   `json:"total_count"`
	Items      []FoodLog `json:"items"`
}

func (v ListFoodLogsResponse) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["total_count"] = v.TotalCount
	m["items"] = v.Items
	return json.Marshal(m)
}
func (v ListFoodLogsResponse) String() string   { return "january.ListFoodLogsResponse{[REDACTED]}" }
func (v ListFoodLogsResponse) GoString() string { return v.String() }

// LoggedFood is generated from the January contract.
type LoggedFood struct {
	ID              FoodID              `json:"id"`
	Name            string              `json:"name"`
	BrandName       Optional[string]    `json:"brand_name"`
	ImageURL        Optional[string]    `json:"image_url"`
	GlycemicIndex   Optional[float64]   `json:"glycemic_index"`
	GlycemicLoad    Optional[float64]   `json:"glycemic_load"`
	Nutrients       NutritionFacts      `json:"nutrients"`
	ConsumedServing FoodLogInputServing `json:"consumed_serving"`
	ServingDetails  ServingDetails      `json:"serving_details"`
}

func (v LoggedFood) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["id"] = v.ID
	m["name"] = v.Name
	putOptional(m, "brand_name", v.BrandName)
	putOptional(m, "image_url", v.ImageURL)
	putOptional(m, "glycemic_index", v.GlycemicIndex)
	putOptional(m, "glycemic_load", v.GlycemicLoad)
	m["nutrients"] = v.Nutrients
	m["consumed_serving"] = v.ConsumedServing
	m["serving_details"] = v.ServingDetails
	return json.Marshal(m)
}
func (v LoggedFood) String() string   { return "january.LoggedFood{[REDACTED]}" }
func (v LoggedFood) GoString() string { return v.String() }

// LookupFoodByBarcodeRequest is generated from the January contract.
type LookupFoodByBarcodeRequest struct {
	EndUserID string  `json:"x-end-user-id,omitempty"`
	UPC       Barcode `json:"upc"`
}

func (v LookupFoodByBarcodeRequest) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	if v.EndUserID != "" {
		m["x-end-user-id"] = v.EndUserID
	}
	m["upc"] = v.UPC
	return json.Marshal(m)
}
func (v LookupFoodByBarcodeRequest) String() string {
	return "january.LookupFoodByBarcodeRequest{[REDACTED]}"
}
func (v LookupFoodByBarcodeRequest) GoString() string { return v.String() }

// MedicalCondition accepts unknown future response enum values.
type MedicalCondition = string

const (
	MedicalConditionType2Diabetes MedicalCondition = "type_2_diabetes"
	MedicalConditionPrediabetes   MedicalCondition = "prediabetes"
)

// MintClientTokenRequest is generated from the January contract.
type MintClientTokenRequest struct {
	EndUserID  string             `json:"end_user_id"`
	Scopes     Optional[[]string] `json:"scopes"`
	TTLSeconds Optional[float64]  `json:"ttl_seconds"`
}

func (v MintClientTokenRequest) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["end_user_id"] = v.EndUserID
	putOptional(m, "scopes", v.Scopes)
	putOptional(m, "ttl_seconds", v.TTLSeconds)
	return json.Marshal(m)
}
func (v MintClientTokenRequest) String() string   { return "january.MintClientTokenRequest{[REDACTED]}" }
func (v MintClientTokenRequest) GoString() string { return v.String() }

// NutrientAmount is generated from the January contract.
type NutrientAmount struct {
	Value float64 `json:"value"`
	Unit  string  `json:"unit"`
}

func (v NutrientAmount) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["value"] = v.Value
	m["unit"] = v.Unit
	return json.Marshal(m)
}
func (v NutrientAmount) String() string   { return "january.NutrientAmount{[REDACTED]}" }
func (v NutrientAmount) GoString() string { return v.String() }

// NutritionFacts is generated from the January contract.
type NutritionFacts struct {
	Calories         Optional[NutrientAmount] `json:"calories"`
	Protein          Optional[NutrientAmount] `json:"protein"`
	Carbohydrates    Optional[NutrientAmount] `json:"carbohydrates"`
	NetCarbohydrates Optional[NutrientAmount] `json:"net_carbohydrates"`
	TotalFat         Optional[NutrientAmount] `json:"total_fat"`
	TransFat         Optional[NutrientAmount] `json:"trans_fat"`
	SaturatedFat     Optional[NutrientAmount] `json:"saturated_fat"`
	Fiber            Optional[NutrientAmount] `json:"fiber"`
	TotalSugars      Optional[NutrientAmount] `json:"total_sugars"`
	AddedSugars      Optional[NutrientAmount] `json:"added_sugars"`
	Cholesterol      Optional[NutrientAmount] `json:"cholesterol"`
	Calcium          Optional[NutrientAmount] `json:"calcium"`
	Iron             Optional[NutrientAmount] `json:"iron"`
	Potassium        Optional[NutrientAmount] `json:"potassium"`
	Sodium           Optional[NutrientAmount] `json:"sodium"`
	VitaminD         Optional[NutrientAmount] `json:"vitamin_d"`
}

func (v NutritionFacts) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	putOptional(m, "calories", v.Calories)
	putOptional(m, "protein", v.Protein)
	putOptional(m, "carbohydrates", v.Carbohydrates)
	putOptional(m, "net_carbohydrates", v.NetCarbohydrates)
	putOptional(m, "total_fat", v.TotalFat)
	putOptional(m, "trans_fat", v.TransFat)
	putOptional(m, "saturated_fat", v.SaturatedFat)
	putOptional(m, "fiber", v.Fiber)
	putOptional(m, "total_sugars", v.TotalSugars)
	putOptional(m, "added_sugars", v.AddedSugars)
	putOptional(m, "cholesterol", v.Cholesterol)
	putOptional(m, "calcium", v.Calcium)
	putOptional(m, "iron", v.Iron)
	putOptional(m, "potassium", v.Potassium)
	putOptional(m, "sodium", v.Sodium)
	putOptional(m, "vitamin_d", v.VitaminD)
	return json.Marshal(m)
}
func (v NutritionFacts) String() string   { return "january.NutritionFacts{[REDACTED]}" }
func (v NutritionFacts) GoString() string { return v.String() }

// PartnerUserID accepts unknown future response enum values.
type PartnerUserID = string

// PredictGlucoseBody is generated from the January contract.
type PredictGlucoseBody struct {
	UserProfile   GlucosePredictionProfile           `json:"user_profile"`
	Foods         []FoodLogInputFood                 `json:"foods"`
	StartTime     string                             `json:"start_time"`
	CGMData       Optional[[]CGMReading]             `json:"cgm_data"`
	ConsumedFoods Optional[[]ConsumedHistoricalFood] `json:"consumed_foods"`
}

func (v PredictGlucoseBody) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["user_profile"] = v.UserProfile
	m["foods"] = v.Foods
	m["start_time"] = v.StartTime
	putOptional(m, "cgm_data", v.CGMData)
	putOptional(m, "consumed_foods", v.ConsumedFoods)
	return json.Marshal(m)
}
func (v PredictGlucoseBody) String() string   { return "january.PredictGlucoseBody{[REDACTED]}" }
func (v PredictGlucoseBody) GoString() string { return v.String() }

// PredictGlucoseRequest is generated from the January contract.
type PredictGlucoseRequest struct {
	EndUserID       string                             `json:"x-end-user-id,omitempty"`
	EndUserTimezone string                             `json:"x-end-user-timezone,omitempty"`
	UserProfile     GlucosePredictionProfile           `json:"user_profile"`
	Foods           []FoodLogInputFood                 `json:"foods"`
	StartTime       string                             `json:"start_time"`
	CGMData         Optional[[]CGMReading]             `json:"cgm_data"`
	ConsumedFoods   Optional[[]ConsumedHistoricalFood] `json:"consumed_foods"`
}

func (v PredictGlucoseRequest) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	if v.EndUserID != "" {
		m["x-end-user-id"] = v.EndUserID
	}
	if v.EndUserTimezone != "" {
		m["x-end-user-timezone"] = v.EndUserTimezone
	}
	m["user_profile"] = v.UserProfile
	m["foods"] = v.Foods
	m["start_time"] = v.StartTime
	putOptional(m, "cgm_data", v.CGMData)
	putOptional(m, "consumed_foods", v.ConsumedFoods)
	return json.Marshal(m)
}
func (v PredictGlucoseRequest) String() string   { return "january.PredictGlucoseRequest{[REDACTED]}" }
func (v PredictGlucoseRequest) GoString() string { return v.String() }

// Restaurant is generated from the January contract.
type Restaurant struct {
	Type     string            `json:"type"`
	ID       string            `json:"id"`
	Name     string            `json:"name"`
	IsChain  Optional[bool]    `json:"is_chain"`
	Distance Optional[float64] `json:"distance"`
	City     Optional[string]  `json:"city"`
	Address1 Optional[string]  `json:"address1"`
	Address2 Optional[string]  `json:"address2"`
}

func (v Restaurant) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["type"] = v.Type
	m["id"] = v.ID
	m["name"] = v.Name
	putOptional(m, "is_chain", v.IsChain)
	putOptional(m, "distance", v.Distance)
	putOptional(m, "city", v.City)
	putOptional(m, "address1", v.Address1)
	putOptional(m, "address2", v.Address2)
	return json.Marshal(m)
}
func (v Restaurant) String() string   { return "january.Restaurant{[REDACTED]}" }
func (v Restaurant) GoString() string { return v.String() }

// RestaurantMenuItem is generated from the January contract.
type RestaurantMenuItem struct {
	Type           string                   `json:"type"`
	ID             RestaurantMenuItemID     `json:"id"`
	Name           string                   `json:"name"`
	RestaurantName string                   `json:"restaurant_name"`
	IsChain        Optional[bool]           `json:"is_chain"`
	Nutrients      Optional[NutritionFacts] `json:"nutrients"`
	GlycemicIndex  Optional[float64]        `json:"glycemic_index"`
	GlycemicLoad   Optional[float64]        `json:"glycemic_load"`
	ImageURL       Optional[string]         `json:"image_url"`
	Distance       Optional[float64]        `json:"distance"`
	Servings       []ServingOption          `json:"servings"`
}

func (v RestaurantMenuItem) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["type"] = v.Type
	m["id"] = v.ID
	m["name"] = v.Name
	m["restaurant_name"] = v.RestaurantName
	putOptional(m, "is_chain", v.IsChain)
	putOptional(m, "nutrients", v.Nutrients)
	putOptional(m, "glycemic_index", v.GlycemicIndex)
	putOptional(m, "glycemic_load", v.GlycemicLoad)
	putOptional(m, "image_url", v.ImageURL)
	putOptional(m, "distance", v.Distance)
	m["servings"] = v.Servings
	return json.Marshal(m)
}
func (v RestaurantMenuItem) String() string   { return "january.RestaurantMenuItem{[REDACTED]}" }
func (v RestaurantMenuItem) GoString() string { return v.String() }

// RestaurantMenuItemID accepts unknown future response enum values.
type RestaurantMenuItemID = string

// RevokeClientTokensRequest is generated from the January contract.
type RevokeClientTokensRequest struct {
	EndUserID string `json:"end_user_id"`
}

func (v RevokeClientTokensRequest) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["end_user_id"] = v.EndUserID
	return json.Marshal(m)
}
func (v RevokeClientTokensRequest) String() string {
	return "january.RevokeClientTokensRequest{[REDACTED]}"
}
func (v RevokeClientTokensRequest) GoString() string { return v.String() }

// ScanFoodPhotoBody is generated from the January contract.
type ScanFoodPhotoBody struct {
	Image string `json:"image"`
}

func (v ScanFoodPhotoBody) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["image"] = v.Image
	return json.Marshal(m)
}
func (v ScanFoodPhotoBody) String() string   { return "january.ScanFoodPhotoBody{[REDACTED]}" }
func (v ScanFoodPhotoBody) GoString() string { return v.String() }

// ScanFoodPhotoRequest is generated from the January contract.
type ScanFoodPhotoRequest struct {
	EndUserID string `json:"x-end-user-id,omitempty"`
	Image     string `json:"image"`
}

func (v ScanFoodPhotoRequest) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	if v.EndUserID != "" {
		m["x-end-user-id"] = v.EndUserID
	}
	m["image"] = v.Image
	return json.Marshal(m)
}
func (v ScanFoodPhotoRequest) String() string   { return "january.ScanFoodPhotoRequest{[REDACTED]}" }
func (v ScanFoodPhotoRequest) GoString() string { return v.String() }

// SearchFoodsByNaturalLanguageBody is generated from the January contract.
type SearchFoodsByNaturalLanguageBody struct {
	Text string `json:"text"`
}

func (v SearchFoodsByNaturalLanguageBody) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["text"] = v.Text
	return json.Marshal(m)
}
func (v SearchFoodsByNaturalLanguageBody) String() string {
	return "january.SearchFoodsByNaturalLanguageBody{[REDACTED]}"
}
func (v SearchFoodsByNaturalLanguageBody) GoString() string { return v.String() }

// SearchFoodsByNaturalLanguageRequest is generated from the January contract.
type SearchFoodsByNaturalLanguageRequest struct {
	EndUserID string `json:"x-end-user-id,omitempty"`
	Query     string `json:"text"`
}

func (v SearchFoodsByNaturalLanguageRequest) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	if v.EndUserID != "" {
		m["x-end-user-id"] = v.EndUserID
	}
	m["text"] = v.Query
	return json.Marshal(m)
}
func (v SearchFoodsByNaturalLanguageRequest) String() string {
	return "january.SearchFoodsByNaturalLanguageRequest{[REDACTED]}"
}
func (v SearchFoodsByNaturalLanguageRequest) GoString() string { return v.String() }

// SearchFoodsRequest is generated from the January contract.
type SearchFoodsRequest struct {
	EndUserID string                 `json:"x-end-user-id,omitempty"`
	Query     string                 `json:"query"`
	Category  Optional[FoodCategory] `json:"category"`
	Limit     Optional[float64]      `json:"limit"`
}

func (v SearchFoodsRequest) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	if v.EndUserID != "" {
		m["x-end-user-id"] = v.EndUserID
	}
	m["query"] = v.Query
	putOptional(m, "category", v.Category)
	putOptional(m, "limit", v.Limit)
	return json.Marshal(m)
}
func (v SearchFoodsRequest) String() string   { return "january.SearchFoodsRequest{[REDACTED]}" }
func (v SearchFoodsRequest) GoString() string { return v.String() }

// SearchRestaurantMenuItemsRequest is generated from the January contract.
type SearchRestaurantMenuItemsRequest struct {
	EndUserID string            `json:"x-end-user-id,omitempty"`
	Radius    Optional[float64] `json:"radius"`
	Limit     Optional[float64] `json:"limit"`
	Query     string            `json:"query"`
	Latitude  float64           `json:"latitude"`
	Longitude float64           `json:"longitude"`
}

func (v SearchRestaurantMenuItemsRequest) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	if v.EndUserID != "" {
		m["x-end-user-id"] = v.EndUserID
	}
	putOptional(m, "radius", v.Radius)
	putOptional(m, "limit", v.Limit)
	m["query"] = v.Query
	m["latitude"] = v.Latitude
	m["longitude"] = v.Longitude
	return json.Marshal(m)
}
func (v SearchRestaurantMenuItemsRequest) String() string {
	return "january.SearchRestaurantMenuItemsRequest{[REDACTED]}"
}
func (v SearchRestaurantMenuItemsRequest) GoString() string { return v.String() }

// SearchRestaurantMenuItemsResponse is generated from the January contract.
type SearchRestaurantMenuItemsResponse struct {
	TotalCount float64              `json:"total_count"`
	Items      []RestaurantMenuItem `json:"items"`
}

func (v SearchRestaurantMenuItemsResponse) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["total_count"] = v.TotalCount
	m["items"] = v.Items
	return json.Marshal(m)
}
func (v SearchRestaurantMenuItemsResponse) String() string {
	return "january.SearchRestaurantMenuItemsResponse{[REDACTED]}"
}
func (v SearchRestaurantMenuItemsResponse) GoString() string { return v.String() }

// SearchRestaurantsRequest is generated from the January contract.
type SearchRestaurantsRequest struct {
	EndUserID string            `json:"x-end-user-id,omitempty"`
	Radius    Optional[float64] `json:"radius"`
	Limit     Optional[float64] `json:"limit"`
	Query     string            `json:"query"`
	Latitude  float64           `json:"latitude"`
	Longitude float64           `json:"longitude"`
}

func (v SearchRestaurantsRequest) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	if v.EndUserID != "" {
		m["x-end-user-id"] = v.EndUserID
	}
	putOptional(m, "radius", v.Radius)
	putOptional(m, "limit", v.Limit)
	m["query"] = v.Query
	m["latitude"] = v.Latitude
	m["longitude"] = v.Longitude
	return json.Marshal(m)
}
func (v SearchRestaurantsRequest) String() string {
	return "january.SearchRestaurantsRequest{[REDACTED]}"
}
func (v SearchRestaurantsRequest) GoString() string { return v.String() }

// SearchRestaurantsResponse is generated from the January contract.
type SearchRestaurantsResponse struct {
	TotalCount float64      `json:"total_count"`
	Items      []Restaurant `json:"items"`
}

func (v SearchRestaurantsResponse) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["total_count"] = v.TotalCount
	m["items"] = v.Items
	return json.Marshal(m)
}
func (v SearchRestaurantsResponse) String() string {
	return "january.SearchRestaurantsResponse{[REDACTED]}"
}
func (v SearchRestaurantsResponse) GoString() string { return v.String() }

// ServingDetails is generated from the January contract.
type ServingDetails struct {
	ID          ServingID         `json:"id"`
	Quantity    float64           `json:"quantity"`
	Unit        string            `json:"unit"`
	WeightGrams Optional[float64] `json:"weight_grams"`
}

func (v ServingDetails) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["id"] = v.ID
	m["quantity"] = v.Quantity
	m["unit"] = v.Unit
	putOptional(m, "weight_grams", v.WeightGrams)
	return json.Marshal(m)
}
func (v ServingDetails) String() string   { return "january.ServingDetails{[REDACTED]}" }
func (v ServingDetails) GoString() string { return v.String() }

// ServingID accepts unknown future response enum values.
type ServingID = int64

// ServingOption is generated from the January contract.
type ServingOption struct {
	ID            ServingID `json:"id"`
	Quantity      float64   `json:"quantity"`
	Unit          string    `json:"unit"`
	ScalingFactor float64   `json:"scaling_factor"`
	WeightGrams   *float64  `json:"weight_grams"`
	IsPrimary     bool      `json:"is_primary"`
}

func (v ServingOption) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["id"] = v.ID
	m["quantity"] = v.Quantity
	m["unit"] = v.Unit
	m["scaling_factor"] = v.ScalingFactor
	m["weight_grams"] = v.WeightGrams
	m["is_primary"] = v.IsPrimary
	return json.Marshal(m)
}
func (v ServingOption) String() string   { return "january.ServingOption{[REDACTED]}" }
func (v ServingOption) GoString() string { return v.String() }

// Sex accepts unknown future response enum values.
type Sex = string

const (
	SexMale   Sex = "male"
	SexFemale Sex = "female"
)

// SuggestFoodAlternativesBody is generated from the January contract.
type SuggestFoodAlternativesBody struct {
	DietRestrictions Optional[[]DietRestriction] `json:"diet_restrictions"`
	DietPreferences  Optional[[]DietPreference]  `json:"diet_preferences"`
}

func (v SuggestFoodAlternativesBody) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	putOptional(m, "diet_restrictions", v.DietRestrictions)
	putOptional(m, "diet_preferences", v.DietPreferences)
	return json.Marshal(m)
}
func (v SuggestFoodAlternativesBody) String() string {
	return "january.SuggestFoodAlternativesBody{[REDACTED]}"
}
func (v SuggestFoodAlternativesBody) GoString() string { return v.String() }

// SuggestFoodAlternativesRequest is generated from the January contract.
type SuggestFoodAlternativesRequest struct {
	EndUserID        string                      `json:"x-end-user-id,omitempty"`
	FoodID           FoodID                      `json:"food_id"`
	DietRestrictions Optional[[]DietRestriction] `json:"diet_restrictions"`
	DietPreferences  Optional[[]DietPreference]  `json:"diet_preferences"`
}

func (v SuggestFoodAlternativesRequest) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	if v.EndUserID != "" {
		m["x-end-user-id"] = v.EndUserID
	}
	m["food_id"] = v.FoodID
	putOptional(m, "diet_restrictions", v.DietRestrictions)
	putOptional(m, "diet_preferences", v.DietPreferences)
	return json.Marshal(m)
}
func (v SuggestFoodAlternativesRequest) String() string {
	return "january.SuggestFoodAlternativesRequest{[REDACTED]}"
}
func (v SuggestFoodAlternativesRequest) GoString() string { return v.String() }

// SuggestFoodAlternativesResponse is generated from the January contract.
type SuggestFoodAlternativesResponse struct {
	Alternatives []FoodAlternative `json:"alternatives"`
}

func (v SuggestFoodAlternativesResponse) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["alternatives"] = v.Alternatives
	return json.Marshal(m)
}
func (v SuggestFoodAlternativesResponse) String() string {
	return "january.SuggestFoodAlternativesResponse{[REDACTED]}"
}
func (v SuggestFoodAlternativesResponse) GoString() string { return v.String() }

// UpdateFoodLogBody is generated from the January contract.
type UpdateFoodLogBody struct {
	Foods        Optional[[]FoodLogInputFood] `json:"foods"`
	TimestampUTC Optional[string]             `json:"timestamp_utc"`
	Name         Optional[string]             `json:"name"`
}

func (v UpdateFoodLogBody) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	putOptional(m, "foods", v.Foods)
	putOptional(m, "timestamp_utc", v.TimestampUTC)
	putOptional(m, "name", v.Name)
	return json.Marshal(m)
}
func (v UpdateFoodLogBody) String() string   { return "january.UpdateFoodLogBody{[REDACTED]}" }
func (v UpdateFoodLogBody) GoString() string { return v.String() }

// UpdateFoodLogRequest is generated from the January contract.
type UpdateFoodLogRequest struct {
	EndUserID       string                       `json:"x-end-user-id,omitempty"`
	EndUserTimezone string                       `json:"x-end-user-timezone,omitempty"`
	LogID           FoodLogID                    `json:"log_id"`
	Foods           Optional[[]FoodLogInputFood] `json:"foods"`
	TimestampUTC    Optional[string]             `json:"timestamp_utc"`
	Name            Optional[string]             `json:"name"`
}

func (v UpdateFoodLogRequest) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	if v.EndUserID != "" {
		m["x-end-user-id"] = v.EndUserID
	}
	if v.EndUserTimezone != "" {
		m["x-end-user-timezone"] = v.EndUserTimezone
	}
	m["log_id"] = v.LogID
	putOptional(m, "foods", v.Foods)
	putOptional(m, "timestamp_utc", v.TimestampUTC)
	putOptional(m, "name", v.Name)
	return json.Marshal(m)
}
func (v UpdateFoodLogRequest) String() string   { return "january.UpdateFoodLogRequest{[REDACTED]}" }
func (v UpdateFoodLogRequest) GoString() string { return v.String() }

// Weight is generated from the January contract.
type Weight struct {
	Value float64    `json:"value"`
	Unit  WeightUnit `json:"unit"`
}

func (v Weight) MarshalJSON() ([]byte, error) {
	m := map[string]any{}
	m["value"] = v.Value
	m["unit"] = v.Unit
	return json.Marshal(m)
}
func (v Weight) String() string   { return "january.Weight{[REDACTED]}" }
func (v Weight) GoString() string { return v.String() }

// WeightUnit accepts unknown future response enum values.
type WeightUnit = string

const (
	WeightUnitLb WeightUnit = "lb"
	WeightUnitKg WeightUnit = "kg"
)

// ClientScope preserves the prototype alias.
type ClientScope = string

const (
	ScopeFoodsRead       = "foods:read"
	ScopeFoodScansWrite  = "food_scans:write"
	ScopeFoodLogsRead    = "food_logs:read"
	ScopeFoodLogsWrite   = "food_logs:write"
	ScopeGlucoseRead     = "glucose:read"
	ScopeRestaurantsRead = "restaurants:read"
)
