// Code generated by partner-api-contract/tools/server-sdk/go.mjs. DO NOT EDIT.
package january

import (
	"context"
	"encoding/json"
	"math"
	"strings"
)

const defaultBaseURL = "https://partners.january.ai"

// Client is concurrency-safe. Do not reassign its public resource handles.
type Client struct {
	transport    *transport
	Foods        *FoodsService
	Restaurants  *RestaurantsService
	FoodAnalysis *FoodAnalysisService
	FoodLogs     *FoodLogsService
	Glucose      *GlucoseService
	ClientTokens *ClientTokensService // Deprecated compatibility alias.
}

// UserClient is a user-scoped view without privileged root operations.
type UserClient struct {
	Foods        *FoodsService
	Restaurants  *RestaurantsService
	FoodAnalysis *FoodAnalysisService
	FoodLogs     *FoodLogsService
	Glucose      *GlucoseService
}
type FoodsService struct{ service }
type RestaurantsService struct{ service }
type FoodAnalysisService struct{ service }
type FoodLogsService struct{ service }
type GlucoseService struct{ service }

func newGeneratedClient(t *transport) *Client {
	return &Client{transport: t, Foods: &FoodsService{service{transport: t}}, Restaurants: &RestaurantsService{service{transport: t}}, FoodAnalysis: &FoodAnalysisService{service{transport: t}}, FoodLogs: &FoodLogsService{service{transport: t}}, Glucose: &GlucoseService{service{transport: t}}}
}
func newGeneratedUserClient(t *transport, u userContext) *UserClient {
	return &UserClient{Foods: &FoodsService{service{transport: t, user: u}}, Restaurants: &RestaurantsService{service{transport: t, user: u}}, FoodAnalysis: &FoodAnalysisService{service{transport: t, user: u}}, FoodLogs: &FoodLogsService{service{transport: t, user: u}}, Glucose: &GlucoseService{service{transport: t, user: u}}}
}

var opSearchFoods = operation{ID: "searchFoods", Method: "GET", Path: "/v1.2/foods", Parameters: []parameter{{Name: "x-end-user-id", In: "header", Required: false, Explode: false, Schema: json.RawMessage("{\"$ref\":\"#/components/schemas/PartnerUserId\"}")}, {Name: "query", In: "query", Required: true, Explode: true, Schema: json.RawMessage("{\"maxLength\":256,\"type\":\"string\"}")}, {Name: "category", In: "query", Required: false, Explode: true, Schema: json.RawMessage("{\"$ref\":\"#/components/schemas/FoodCategory\"}")}, {Name: "limit", In: "query", Required: false, Explode: true, Schema: json.RawMessage("{\"minimum\":1,\"maximum\":40,\"type\":\"number\"}")}}, BodyFields: []string{}, RequiredBody: false, BodySchema: json.RawMessage("{}"), ResponseSchemas: map[int]json.RawMessage{200: json.RawMessage("{\"$ref\":\"#/components/schemas/FoodSearchResults\"}")}}

// Search executes searchFoods without automatic retries.
func (c *FoodsService) Search(ctx context.Context, request SearchFoodsRequest) (*FoodSearchResults, *Response, error) {
	var result FoodSearchResults
	response, err := execute(ctx, c.service, opSearchFoods, request, &result)
	if err != nil {
		return nil, response, err
	}
	return &result, response, nil
}

var opAutocompleteFoods = operation{ID: "autocompleteFoods", Method: "GET", Path: "/v1.2/foods/autocomplete", Parameters: []parameter{{Name: "x-end-user-id", In: "header", Required: false, Explode: false, Schema: json.RawMessage("{\"$ref\":\"#/components/schemas/PartnerUserId\"}")}, {Name: "query", In: "query", Required: true, Explode: true, Schema: json.RawMessage("{\"maxLength\":64,\"type\":\"string\"}")}, {Name: "category", In: "query", Required: false, Explode: true, Schema: json.RawMessage("{\"$ref\":\"#/components/schemas/AutocompleteFoodCategory\"}")}, {Name: "limit", In: "query", Required: false, Explode: true, Schema: json.RawMessage("{\"minimum\":1,\"maximum\":20,\"type\":\"number\"}")}}, BodyFields: []string{}, RequiredBody: false, BodySchema: json.RawMessage("{}"), ResponseSchemas: map[int]json.RawMessage{200: json.RawMessage("{\"$ref\":\"#/components/schemas/AutocompleteFoodsResponse\"}")}}

// Autocomplete executes autocompleteFoods without automatic retries.
func (c *FoodsService) Autocomplete(ctx context.Context, request AutocompleteFoodsRequest) (*AutocompleteFoodsResponse, *Response, error) {
	var result AutocompleteFoodsResponse
	response, err := execute(ctx, c.service, opAutocompleteFoods, request, &result)
	if err != nil {
		return nil, response, err
	}
	return &result, response, nil
}

var opSuggestFoodAlternatives = operation{ID: "suggestFoodAlternatives", Method: "POST", Path: "/v1.2/foods/{food_id}/alternatives", Parameters: []parameter{{Name: "x-end-user-id", In: "header", Required: false, Explode: false, Schema: json.RawMessage("{\"$ref\":\"#/components/schemas/PartnerUserId\"}")}, {Name: "food_id", In: "path", Required: true, Explode: false, Schema: json.RawMessage("{\"$ref\":\"#/components/schemas/FoodId\"}")}}, BodyFields: []string{"diet_restrictions", "diet_preferences"}, RequiredBody: true, BodySchema: json.RawMessage("{\"type\":\"object\",\"properties\":{\"diet_restrictions\":{\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/DietRestriction\"},\"minItems\":1},\"diet_preferences\":{\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/DietPreference\"},\"minItems\":1}}}"), ResponseSchemas: map[int]json.RawMessage{200: json.RawMessage("{\"$ref\":\"#/components/schemas/SuggestFoodAlternativesResponse\"}")}}

// SuggestAlternatives executes suggestFoodAlternatives without automatic retries.
func (c *FoodsService) SuggestAlternatives(ctx context.Context, request SuggestFoodAlternativesRequest) (*SuggestFoodAlternativesResponse, *Response, error) {
	var result SuggestFoodAlternativesResponse
	response, err := execute(ctx, c.service, opSuggestFoodAlternatives, request, &result)
	if err != nil {
		return nil, response, err
	}
	return &result, response, nil
}

var opLookupFoodByBarcode = operation{ID: "lookupFoodByBarcode", Method: "GET", Path: "/v1.2/foods/barcode/{upc}", Parameters: []parameter{{Name: "x-end-user-id", In: "header", Required: false, Explode: false, Schema: json.RawMessage("{\"$ref\":\"#/components/schemas/PartnerUserId\"}")}, {Name: "upc", In: "path", Required: true, Explode: false, Schema: json.RawMessage("{\"$ref\":\"#/components/schemas/Barcode\"}")}}, BodyFields: []string{}, RequiredBody: false, BodySchema: json.RawMessage("{}"), ResponseSchemas: map[int]json.RawMessage{200: json.RawMessage("{\"$ref\":\"#/components/schemas/FoodSearchResults\"}")}}

// LookupBarcode executes lookupFoodByBarcode without automatic retries.
func (c *FoodsService) LookupBarcode(ctx context.Context, request LookupFoodByBarcodeRequest) (*FoodSearchResults, *Response, error) {
	var result FoodSearchResults
	response, err := execute(ctx, c.service, opLookupFoodByBarcode, request, &result)
	if err != nil {
		return nil, response, err
	}
	return &result, response, nil
}

var opGetFood = operation{ID: "getFood", Method: "GET", Path: "/v1.2/foods/{food_id}", Parameters: []parameter{{Name: "x-end-user-id", In: "header", Required: false, Explode: false, Schema: json.RawMessage("{\"$ref\":\"#/components/schemas/PartnerUserId\"}")}, {Name: "food_id", In: "path", Required: true, Explode: false, Schema: json.RawMessage("{\"$ref\":\"#/components/schemas/FoodId\"}")}}, BodyFields: []string{}, RequiredBody: false, BodySchema: json.RawMessage("{}"), ResponseSchemas: map[int]json.RawMessage{200: json.RawMessage("{\"$ref\":\"#/components/schemas/FoodSearchItem\"}")}}

// Get executes getFood without automatic retries.
func (c *FoodsService) Get(ctx context.Context, request GetFoodRequest) (*FoodSearchItem, *Response, error) {
	var result FoodSearchItem
	response, err := execute(ctx, c.service, opGetFood, request, &result)
	if err != nil {
		return nil, response, err
	}
	return &result, response, nil
}

var opSearchRestaurants = operation{ID: "searchRestaurants", Method: "GET", Path: "/v1.2/restaurants", Parameters: []parameter{{Name: "x-end-user-id", In: "header", Required: false, Explode: false, Schema: json.RawMessage("{\"$ref\":\"#/components/schemas/PartnerUserId\"}")}, {Name: "radius", In: "query", Required: false, Explode: true, Schema: json.RawMessage("{\"minimum\":1,\"maximum\":17000,\"type\":\"number\"}")}, {Name: "limit", In: "query", Required: false, Explode: true, Schema: json.RawMessage("{\"minimum\":1,\"maximum\":100,\"type\":\"number\"}")}, {Name: "query", In: "query", Required: true, Explode: true, Schema: json.RawMessage("{\"maxLength\":256,\"type\":\"string\"}")}, {Name: "latitude", In: "query", Required: true, Explode: true, Schema: json.RawMessage("{\"minimum\":-90,\"maximum\":90,\"type\":\"number\"}")}, {Name: "longitude", In: "query", Required: true, Explode: true, Schema: json.RawMessage("{\"minimum\":-180,\"maximum\":180,\"type\":\"number\"}")}}, BodyFields: []string{}, RequiredBody: false, BodySchema: json.RawMessage("{}"), ResponseSchemas: map[int]json.RawMessage{200: json.RawMessage("{\"$ref\":\"#/components/schemas/SearchRestaurantsResponse\"}")}}

// Search executes searchRestaurants without automatic retries.
func (c *RestaurantsService) Search(ctx context.Context, request SearchRestaurantsRequest) (*SearchRestaurantsResponse, *Response, error) {
	var result SearchRestaurantsResponse
	response, err := execute(ctx, c.service, opSearchRestaurants, request, &result)
	if err != nil {
		return nil, response, err
	}
	return &result, response, nil
}

var opSearchRestaurantMenuItems = operation{ID: "searchRestaurantMenuItems", Method: "GET", Path: "/v1.2/restaurants/menu-items", Parameters: []parameter{{Name: "x-end-user-id", In: "header", Required: false, Explode: false, Schema: json.RawMessage("{\"$ref\":\"#/components/schemas/PartnerUserId\"}")}, {Name: "radius", In: "query", Required: false, Explode: true, Schema: json.RawMessage("{\"minimum\":1,\"maximum\":17000,\"type\":\"number\"}")}, {Name: "limit", In: "query", Required: false, Explode: true, Schema: json.RawMessage("{\"minimum\":1,\"maximum\":100,\"type\":\"number\"}")}, {Name: "query", In: "query", Required: true, Explode: true, Schema: json.RawMessage("{\"maxLength\":256,\"type\":\"string\"}")}, {Name: "latitude", In: "query", Required: true, Explode: true, Schema: json.RawMessage("{\"minimum\":-90,\"maximum\":90,\"type\":\"number\"}")}, {Name: "longitude", In: "query", Required: true, Explode: true, Schema: json.RawMessage("{\"minimum\":-180,\"maximum\":180,\"type\":\"number\"}")}}, BodyFields: []string{}, RequiredBody: false, BodySchema: json.RawMessage("{}"), ResponseSchemas: map[int]json.RawMessage{200: json.RawMessage("{\"$ref\":\"#/components/schemas/SearchRestaurantMenuItemsResponse\"}")}}

// SearchMenuItems executes searchRestaurantMenuItems without automatic retries.
func (c *RestaurantsService) SearchMenuItems(ctx context.Context, request SearchRestaurantMenuItemsRequest) (*SearchRestaurantMenuItemsResponse, *Response, error) {
	var result SearchRestaurantMenuItemsResponse
	response, err := execute(ctx, c.service, opSearchRestaurantMenuItems, request, &result)
	if err != nil {
		return nil, response, err
	}
	return &result, response, nil
}

var opScanFoodPhoto = operation{ID: "scanFoodPhoto", Method: "POST", Path: "/v1.2/food-scans/photo", Parameters: []parameter{{Name: "x-end-user-id", In: "header", Required: false, Explode: false, Schema: json.RawMessage("{\"$ref\":\"#/components/schemas/PartnerUserId\"}")}}, BodyFields: []string{"image"}, RequiredBody: true, BodySchema: json.RawMessage("{\"type\":\"object\",\"properties\":{\"image\":{\"type\":\"string\"}},\"required\":[\"image\"]}"), ResponseSchemas: map[int]json.RawMessage{200: json.RawMessage("{\"$ref\":\"#/components/schemas/FoodScan\"}")}}

// AnalyzePhoto executes scanFoodPhoto without automatic retries.
func (c *FoodAnalysisService) AnalyzePhoto(ctx context.Context, request ScanFoodPhotoRequest) (*FoodScan, *Response, error) {
	var result FoodScan
	response, err := execute(ctx, c.service, opScanFoodPhoto, request, &result)
	if err != nil {
		return nil, response, err
	}
	return &result, response, nil
}

var opSearchFoodsByNaturalLanguage = operation{ID: "searchFoodsByNaturalLanguage", Method: "POST", Path: "/v1.2/food-scans/text", Parameters: []parameter{{Name: "x-end-user-id", In: "header", Required: false, Explode: false, Schema: json.RawMessage("{\"$ref\":\"#/components/schemas/PartnerUserId\"}")}}, BodyFields: []string{"text"}, RequiredBody: true, BodySchema: json.RawMessage("{\"type\":\"object\",\"properties\":{\"text\":{\"type\":\"string\",\"maxLength\":512}},\"required\":[\"text\"]}"), ResponseSchemas: map[int]json.RawMessage{200: json.RawMessage("{\"$ref\":\"#/components/schemas/FoodScan\"}")}}

// AnalyzeDescription executes searchFoodsByNaturalLanguage without automatic retries.
func (c *FoodAnalysisService) AnalyzeDescription(ctx context.Context, request SearchFoodsByNaturalLanguageRequest) (*FoodScan, *Response, error) {
	var result FoodScan
	response, err := execute(ctx, c.service, opSearchFoodsByNaturalLanguage, request, &result)
	if err != nil {
		return nil, response, err
	}
	return &result, response, nil
}

var opCorrectPhotoScan = operation{ID: "correctPhotoScan", Method: "POST", Path: "/v1.2/food-scans/corrections", Parameters: []parameter{{Name: "x-end-user-id", In: "header", Required: false, Explode: false, Schema: json.RawMessage("{\"$ref\":\"#/components/schemas/PartnerUserId\"}")}}, BodyFields: []string{"meal_name", "detections", "user_input"}, RequiredBody: true, BodySchema: json.RawMessage("{\"type\":\"object\",\"properties\":{\"meal_name\":{\"type\":\"string\"},\"detections\":{\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/FoodDetection\"}},\"user_input\":{\"type\":\"string\"}},\"required\":[\"detections\",\"user_input\"]}"), ResponseSchemas: map[int]json.RawMessage{200: json.RawMessage("{\"$ref\":\"#/components/schemas/FoodScan\"}")}}

// Correct executes correctPhotoScan without automatic retries.
func (c *FoodAnalysisService) Correct(ctx context.Context, request CorrectPhotoScanRequest) (*FoodScan, *Response, error) {
	var result FoodScan
	response, err := execute(ctx, c.service, opCorrectPhotoScan, request, &result)
	if err != nil {
		return nil, response, err
	}
	return &result, response, nil
}

var opCreateFoodLog = operation{ID: "createFoodLog", Method: "POST", Path: "/v1.2/food-logs", Parameters: []parameter{{Name: "x-end-user-id", In: "header", Required: true, Explode: false, Schema: json.RawMessage("{\"$ref\":\"#/components/schemas/PartnerUserId\"}")}, {Name: "x-end-user-timezone", In: "header", Required: false, Explode: false, Schema: json.RawMessage("{\"type\":\"string\"}")}}, BodyFields: []string{"foods", "timestamp_utc", "name"}, RequiredBody: true, BodySchema: json.RawMessage("{\"type\":\"object\",\"properties\":{\"foods\":{\"maxItems\":100,\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/FoodLogInputFood\"}},\"timestamp_utc\":{\"type\":\"string\",\"format\":\"date-time\"},\"name\":{\"type\":\"string\",\"maxLength\":256}},\"required\":[\"foods\"]}"), ResponseSchemas: map[int]json.RawMessage{200: json.RawMessage("{\"$ref\":\"#/components/schemas/FoodLog\"}")}}

// Create executes createFoodLog without automatic retries.
func (c *FoodLogsService) Create(ctx context.Context, request CreateFoodLogRequest) (*FoodLog, *Response, error) {
	var result FoodLog
	response, err := execute(ctx, c.service, opCreateFoodLog, request, &result)
	if err != nil {
		return nil, response, err
	}
	return &result, response, nil
}

var opListFoodLogs = operation{ID: "listFoodLogs", Method: "GET", Path: "/v1.2/food-logs", Parameters: []parameter{{Name: "x-end-user-id", In: "header", Required: true, Explode: false, Schema: json.RawMessage("{\"$ref\":\"#/components/schemas/PartnerUserId\"}")}, {Name: "x-end-user-timezone", In: "header", Required: false, Explode: false, Schema: json.RawMessage("{\"type\":\"string\"}")}, {Name: "start", In: "query", Required: true, Explode: true, Schema: json.RawMessage("{\"format\":\"date\",\"type\":\"string\"}")}, {Name: "end", In: "query", Required: true, Explode: true, Schema: json.RawMessage("{\"format\":\"date\",\"type\":\"string\"}")}}, BodyFields: []string{}, RequiredBody: false, BodySchema: json.RawMessage("{}"), ResponseSchemas: map[int]json.RawMessage{200: json.RawMessage("{\"$ref\":\"#/components/schemas/ListFoodLogsResponse\"}")}}

// List executes listFoodLogs without automatic retries.
func (c *FoodLogsService) List(ctx context.Context, request ListFoodLogsRequest) (*ListFoodLogsResponse, *Response, error) {
	var result ListFoodLogsResponse
	response, err := execute(ctx, c.service, opListFoodLogs, request, &result)
	if err != nil {
		return nil, response, err
	}
	return &result, response, nil
}

var opUpdateFoodLog = operation{ID: "updateFoodLog", Method: "PATCH", Path: "/v1.2/food-logs/{log_id}", Parameters: []parameter{{Name: "x-end-user-id", In: "header", Required: true, Explode: false, Schema: json.RawMessage("{\"$ref\":\"#/components/schemas/PartnerUserId\"}")}, {Name: "x-end-user-timezone", In: "header", Required: false, Explode: false, Schema: json.RawMessage("{\"type\":\"string\"}")}, {Name: "log_id", In: "path", Required: true, Explode: false, Schema: json.RawMessage("{\"$ref\":\"#/components/schemas/FoodLogId\"}")}}, BodyFields: []string{"foods", "timestamp_utc", "name"}, RequiredBody: true, BodySchema: json.RawMessage("{\"type\":\"object\",\"properties\":{\"foods\":{\"maxItems\":100,\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/FoodLogInputFood\"}},\"timestamp_utc\":{\"type\":\"string\"},\"name\":{\"type\":\"string\",\"maxLength\":256}}}"), ResponseSchemas: map[int]json.RawMessage{200: json.RawMessage("{\"$ref\":\"#/components/schemas/FoodLog\"}")}}

// Update executes updateFoodLog without automatic retries.
func (c *FoodLogsService) Update(ctx context.Context, request UpdateFoodLogRequest) (*FoodLog, *Response, error) {
	var result FoodLog
	response, err := execute(ctx, c.service, opUpdateFoodLog, request, &result)
	if err != nil {
		return nil, response, err
	}
	return &result, response, nil
}

var opDeleteFoodLog = operation{ID: "deleteFoodLog", Method: "DELETE", Path: "/v1.2/food-logs/{log_id}", Parameters: []parameter{{Name: "x-end-user-id", In: "header", Required: true, Explode: false, Schema: json.RawMessage("{\"$ref\":\"#/components/schemas/PartnerUserId\"}")}, {Name: "x-end-user-timezone", In: "header", Required: false, Explode: false, Schema: json.RawMessage("{\"type\":\"string\"}")}, {Name: "log_id", In: "path", Required: true, Explode: false, Schema: json.RawMessage("{\"$ref\":\"#/components/schemas/FoodLogId\"}")}}, BodyFields: []string{}, RequiredBody: false, BodySchema: json.RawMessage("{}"), ResponseSchemas: map[int]json.RawMessage{200: json.RawMessage("{\"$ref\":\"#/components/schemas/DeleteFoodLogResponse\"}")}}

// Delete executes deleteFoodLog without automatic retries.
func (c *FoodLogsService) Delete(ctx context.Context, request DeleteFoodLogRequest) (*DeleteFoodLogResponse, *Response, error) {
	var result DeleteFoodLogResponse
	response, err := execute(ctx, c.service, opDeleteFoodLog, request, &result)
	if err != nil {
		return nil, response, err
	}
	return &result, response, nil
}

var opPredictGlucose = operation{ID: "predictGlucose", Method: "POST", Path: "/v1.2/glucose/predictions", Parameters: []parameter{{Name: "x-end-user-id", In: "header", Required: false, Explode: false, Schema: json.RawMessage("{\"$ref\":\"#/components/schemas/PartnerUserId\"}")}, {Name: "x-end-user-timezone", In: "header", Required: false, Explode: false, Schema: json.RawMessage("{\"type\":\"string\"}")}}, BodyFields: []string{"user_profile", "foods", "start_time", "cgm_data", "consumed_foods"}, RequiredBody: true, BodySchema: json.RawMessage("{\"type\":\"object\",\"properties\":{\"user_profile\":{\"$ref\":\"#/components/schemas/GlucosePredictionProfile\"},\"foods\":{\"maxItems\":100,\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/FoodLogInputFood\"}},\"start_time\":{\"type\":\"string\",\"format\":\"date-time\"},\"cgm_data\":{\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/CgmReading\"}},\"consumed_foods\":{\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/ConsumedHistoricalFood\"}}},\"required\":[\"user_profile\",\"foods\",\"start_time\"]}"), ResponseSchemas: map[int]json.RawMessage{200: json.RawMessage("{\"$ref\":\"#/components/schemas/GlucosePrediction\"}")}}

// Predict executes predictGlucose without automatic retries.
func (c *GlucoseService) Predict(ctx context.Context, request PredictGlucoseRequest) (*GlucosePrediction, *Response, error) {
	var result GlucosePrediction
	response, err := execute(ctx, c.service, opPredictGlucose, request, &result)
	if err != nil {
		return nil, response, err
	}
	return &result, response, nil
}

var opMintClientToken = operation{ID: "mintClientToken", Method: "POST", Path: "/v1.2/auth/client-tokens", Parameters: []parameter{}, BodyFields: []string{"end_user_id", "scopes", "ttl_seconds"}, RequiredBody: true, BodySchema: json.RawMessage("{\"type\":\"object\",\"properties\":{\"end_user_id\":{\"type\":\"string\",\"maxLength\":64},\"scopes\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"enum\":[\"foods:read\",\"food_scans:write\",\"food_logs:read\",\"food_logs:write\",\"glucose:read\",\"restaurants:read\"]}},\"ttl_seconds\":{\"type\":\"number\",\"minimum\":300,\"maximum\":7200}},\"required\":[\"end_user_id\"]}"), ResponseSchemas: map[int]json.RawMessage{201: json.RawMessage("{\"$ref\":\"#/components/schemas/ClientTokenResponseDto\"}")}}

// MintClientToken executes mintClientToken without automatic retries.
func (c *Client) MintClientToken(ctx context.Context, request MintClientTokenRequest) (*ClientTokenResponseDto, *Response, error) {
	var result ClientTokenResponseDto
	response, err := execute(ctx, service{transport: c.transport}, opMintClientToken, request, &result)
	if err != nil {
		return nil, response, err
	}
	return &result, response, nil
}

var opRevokeClientTokens = operation{ID: "revokeClientTokens", Method: "DELETE", Path: "/v1.2/auth/client-tokens", Parameters: []parameter{{Name: "end_user_id", In: "query", Required: true, Explode: true, Schema: json.RawMessage("{\"maxLength\":64,\"type\":\"string\"}")}}, BodyFields: []string{}, RequiredBody: false, BodySchema: json.RawMessage("{}"), ResponseSchemas: map[int]json.RawMessage{204: nil}}

// RevokeClientTokens executes revokeClientTokens without automatic retries.
// Exactly one DELETE. Response.RevokedCount exposes X-Revoked-Count.
func (c *Client) RevokeClientTokens(ctx context.Context, request RevokeClientTokensRequest) (*Response, error) {
	return execute(ctx, service{transport: c.transport}, opRevokeClientTokens, request, nil)
}

var opCredits = operation{ID: "credits", Method: "GET", Path: "/v1.2/credits", Parameters: []parameter{{Name: "x-end-user-id", In: "header", Required: false, Explode: false, Schema: json.RawMessage("{\"type\":\"string\"}")}}, BodyFields: []string{}, RequiredBody: false, BodySchema: json.RawMessage("{}"), ResponseSchemas: map[int]json.RawMessage{200: json.RawMessage("{\"$ref\":\"#/components/schemas/CreditsResponseDto\"}")}}

// Credits executes credits without automatic retries.
func (c *Client) Credits(ctx context.Context, requests ...CreditsRequest) (*CreditsResponseDto, *Response, error) {
	var request CreditsRequest
	if len(requests) > 1 {
		return nil, nil, ErrInvalidInput
	}
	if len(requests) == 1 {
		request = requests[0]
	}
	var result CreditsResponseDto
	response, err := execute(ctx, service{transport: c.transport}, opCredits, request, &result)
	if err != nil {
		return nil, response, err
	}
	return &result, response, nil
}

var generatedSchemas = map[string]json.RawMessage{
	"ActivityLevel":                     json.RawMessage("{\"type\":\"string\",\"enum\":[\"sedentary\",\"lightly_active\",\"moderately_active\",\"very_active\"]}"),
	"AlternativeFood":                   json.RawMessage("{\"type\":\"object\",\"properties\":{\"id\":{\"$ref\":\"#/components/schemas/FoodId\"},\"name\":{\"type\":\"string\"},\"brand_name\":{\"type\":\"string\"},\"nutrients\":{\"$ref\":\"#/components/schemas/CompleteScanNutritionFacts\"},\"servings\":{\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/AlternativeServing\"}}},\"required\":[\"name\",\"nutrients\"]}"),
	"AlternativeServing":                json.RawMessage("{\"type\":\"object\",\"properties\":{\"id\":{\"$ref\":\"#/components/schemas/ServingId\"},\"quantity\":{\"type\":\"number\"},\"unit\":{\"type\":\"string\"}},\"required\":[\"id\",\"unit\"]}"),
	"ApiErrorDto":                       json.RawMessage("{\"type\":\"object\",\"properties\":{\"message\":{\"type\":\"string\"},\"code\":{\"type\":\"string\"},\"docs_url\":{\"type\":\"string\"}},\"required\":[\"message\",\"code\",\"docs_url\"]}"),
	"AutocompleteFoodCategory":          json.RawMessage("{\"enum\":[\"general\",\"branded\"],\"type\":\"string\"}"),
	"AutocompleteFoodsResponse":         json.RawMessage("{\"type\":\"object\",\"properties\":{\"items\":{\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/FoodSuggestion\"}}},\"required\":[\"items\"]}"),
	"Barcode":                           json.RawMessage("{\"type\":\"string\",\"pattern\":\"^[0-9]{6,14}$\"}"),
	"CgmReading":                        json.RawMessage("{\"type\":\"object\",\"properties\":{\"timestamp\":{\"type\":\"string\",\"format\":\"date-time\"},\"value\":{\"type\":\"number\"}},\"required\":[\"timestamp\",\"value\"]}"),
	"ClientTokenResponseDto":            json.RawMessage("{\"type\":\"object\",\"properties\":{\"token\":{\"type\":\"string\"},\"expires_in\":{\"type\":\"number\"},\"expires_at\":{\"type\":\"string\"},\"end_user_id\":{\"type\":\"string\"},\"scopes\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"enum\":[\"foods:read\",\"food_scans:write\",\"food_logs:read\",\"food_logs:write\",\"glucose:read\",\"restaurants:read\"]}}},\"required\":[\"token\",\"expires_in\",\"expires_at\",\"end_user_id\",\"scopes\"]}"),
	"CompleteScanNutritionFacts":        json.RawMessage("{\"type\":\"object\",\"properties\":{\"calories\":{\"$ref\":\"#/components/schemas/NutrientAmount\"},\"protein\":{\"$ref\":\"#/components/schemas/NutrientAmount\"},\"carbohydrates\":{\"$ref\":\"#/components/schemas/NutrientAmount\"},\"net_carbohydrates\":{\"$ref\":\"#/components/schemas/NutrientAmount\"},\"total_fat\":{\"$ref\":\"#/components/schemas/NutrientAmount\"},\"saturated_fat\":{\"$ref\":\"#/components/schemas/NutrientAmount\"},\"fiber\":{\"$ref\":\"#/components/schemas/NutrientAmount\"},\"total_sugars\":{\"$ref\":\"#/components/schemas/NutrientAmount\"},\"added_sugars\":{\"$ref\":\"#/components/schemas/NutrientAmount\"},\"sodium\":{\"$ref\":\"#/components/schemas/NutrientAmount\"}}}"),
	"ConfidenceScore":                   json.RawMessage("{\"type\":\"string\",\"enum\":[\"high\",\"medium\",\"low\"]}"),
	"ConsumedHistoricalFood":            json.RawMessage("{\"type\":\"object\",\"properties\":{\"timestamp\":{\"type\":\"string\",\"format\":\"date-time\"},\"id\":{\"$ref\":\"#/components/schemas/FoodId\"},\"serving\":{\"$ref\":\"#/components/schemas/FoodLogInputServing\"}},\"required\":[\"timestamp\",\"id\",\"serving\"]}"),
	"CorrectPhotoScanBody":              json.RawMessage("{\"type\":\"object\",\"properties\":{\"meal_name\":{\"type\":\"string\"},\"detections\":{\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/FoodDetection\"}},\"user_input\":{\"type\":\"string\"}},\"required\":[\"detections\",\"user_input\"]}"),
	"CreateClientTokenDto":              json.RawMessage("{\"type\":\"object\",\"properties\":{\"end_user_id\":{\"type\":\"string\",\"maxLength\":64},\"scopes\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"enum\":[\"foods:read\",\"food_scans:write\",\"food_logs:read\",\"food_logs:write\",\"glucose:read\",\"restaurants:read\"]}},\"ttl_seconds\":{\"type\":\"number\",\"minimum\":300,\"maximum\":7200}},\"required\":[\"end_user_id\"]}"),
	"CreateFoodLogBody":                 json.RawMessage("{\"type\":\"object\",\"properties\":{\"foods\":{\"maxItems\":100,\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/FoodLogInputFood\"}},\"timestamp_utc\":{\"type\":\"string\",\"format\":\"date-time\"},\"name\":{\"type\":\"string\",\"maxLength\":256}},\"required\":[\"foods\"]}"),
	"CreditsResponseDto":                json.RawMessage("{\"type\":\"object\",\"properties\":{\"plan\":{\"type\":\"string\"},\"period_start\":{\"type\":\"string\"},\"period_end\":{\"type\":\"string\"},\"resets_at\":{\"type\":\"string\"},\"included_credits\":{\"type\":\"number\"},\"used_credits\":{\"type\":\"number\"},\"remaining_credits\":{\"type\":\"number\"}},\"required\":[\"plan\",\"period_start\",\"period_end\",\"resets_at\",\"used_credits\"]}"),
	"DeleteFoodLogResponse":             json.RawMessage("{\"type\":\"object\",\"properties\":{\"status\":{\"type\":\"string\"}},\"required\":[\"status\"]}"),
	"DetectedFood":                      json.RawMessage("{\"type\":\"object\",\"properties\":{\"id\":{\"$ref\":\"#/components/schemas/FoodId\"},\"name\":{\"type\":\"string\"},\"brand_name\":{\"type\":\"string\"},\"nutrients\":{\"$ref\":\"#/components/schemas/CompleteScanNutritionFacts\"},\"servings\":{\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/DetectedServing\"}}},\"required\":[\"name\",\"nutrients\",\"servings\"]}"),
	"DetectedServing":                   json.RawMessage("{\"type\":\"object\",\"properties\":{\"id\":{\"$ref\":\"#/components/schemas/ServingId\"},\"quantity\":{\"type\":\"number\"},\"unit\":{\"type\":\"string\"},\"selected_quantity\":{\"type\":\"number\"}},\"required\":[\"id\",\"unit\"]}"),
	"DietPreference":                    json.RawMessage("{\"type\":\"string\",\"enum\":[\"vegetarian\",\"vegan\",\"keto\",\"paleo\",\"pescatarian\",\"low_carbohydrate\",\"high_protein\",\"kosher\",\"halal\"]}"),
	"DietRestriction":                   json.RawMessage("{\"type\":\"string\",\"enum\":[\"gluten\",\"lactose\",\"yeast\",\"tree_nuts\",\"peanuts\",\"dairy\",\"eggs\",\"sulfites\",\"soy\",\"wheat\",\"shellfish\",\"fish\",\"mushrooms\",\"sesame\",\"msg\",\"caffeine\",\"fodmaps\"]}"),
	"ErrorResponse":                     json.RawMessage("{\"type\":\"object\",\"properties\":{\"message\":{\"type\":\"string\"},\"code\":{\"type\":\"string\"},\"docs_url\":{\"type\":\"string\"}},\"required\":[\"message\",\"code\",\"docs_url\"]}"),
	"FoodAlternative":                   json.RawMessage("{\"type\":\"object\",\"properties\":{\"food\":{\"$ref\":\"#/components/schemas/AlternativeFood\"}},\"required\":[\"food\"]}"),
	"FoodCategory":                      json.RawMessage("{\"enum\":[\"general\",\"branded\",\"recipe\"],\"type\":\"string\"}"),
	"FoodDetection":                     json.RawMessage("{\"type\":\"object\",\"properties\":{\"confidence_score\":{\"$ref\":\"#/components/schemas/ConfidenceScore\"},\"food\":{\"$ref\":\"#/components/schemas/DetectedFood\"}},\"required\":[\"food\"]}"),
	"FoodId":                            json.RawMessage("{\"type\":\"integer\",\"format\":\"int64\",\"minimum\":0,\"maximum\":9007199254740991}"),
	"FoodLog":                           json.RawMessage("{\"type\":\"object\",\"properties\":{\"id\":{\"$ref\":\"#/components/schemas/FoodLogId\"},\"foods\":{\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/LoggedFood\"}},\"timestamp_utc\":{\"type\":\"string\",\"format\":\"january-api-timestamp\"},\"name\":{\"type\":\"string\",\"nullable\":true}},\"required\":[\"id\",\"foods\",\"timestamp_utc\"]}"),
	"FoodLogId":                         json.RawMessage("{\"type\":\"string\",\"format\":\"uuid\"}"),
	"FoodLogInputFood":                  json.RawMessage("{\"type\":\"object\",\"properties\":{\"id\":{\"$ref\":\"#/components/schemas/FoodId\"},\"serving\":{\"$ref\":\"#/components/schemas/FoodLogInputServing\"}},\"required\":[\"id\",\"serving\"]}"),
	"FoodLogInputServing":               json.RawMessage("{\"type\":\"object\",\"properties\":{\"id\":{\"$ref\":\"#/components/schemas/ServingId\"},\"quantity\":{\"type\":\"number\",\"maximum\":10000}},\"required\":[\"id\",\"quantity\"]}"),
	"FoodScan":                          json.RawMessage("{\"type\":\"object\",\"properties\":{\"meal_name\":{\"type\":\"string\"},\"total_nutrients\":{\"allOf\":[{\"$ref\":\"#/components/schemas/CompleteScanNutritionFacts\"}]},\"detections\":{\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/FoodDetection\"}}},\"required\":[\"detections\"]}"),
	"FoodSearchItem":                    json.RawMessage("{\"type\":\"object\",\"properties\":{\"id\":{\"$ref\":\"#/components/schemas/FoodId\"},\"name\":{\"type\":\"string\"},\"brand_name\":{\"type\":\"string\"},\"nutrients\":{\"allOf\":[{\"$ref\":\"#/components/schemas/NutritionFacts\"}]},\"glycemic_index\":{\"type\":\"number\"},\"glycemic_load\":{\"type\":\"number\"},\"image_url\":{\"type\":\"string\"},\"upc\":{\"type\":\"string\"},\"servings\":{\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/ServingOption\"}}},\"required\":[\"id\",\"name\",\"nutrients\",\"servings\"]}"),
	"FoodSearchResults":                 json.RawMessage("{\"type\":\"object\",\"properties\":{\"total_count\":{\"type\":\"number\"},\"items\":{\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/FoodSearchItem\"}}},\"required\":[\"total_count\",\"items\"]}"),
	"FoodSuggestion":                    json.RawMessage("{\"type\":\"object\",\"properties\":{\"id\":{\"$ref\":\"#/components/schemas/FoodId\"},\"name\":{\"type\":\"string\"},\"brand_name\":{\"type\":\"string\"},\"image_url\":{\"type\":\"string\"},\"nutrients\":{\"allOf\":[{\"$ref\":\"#/components/schemas/NutritionFacts\"}]}},\"required\":[\"id\",\"name\"]}"),
	"GlucoseChart":                      json.RawMessage("{\"type\":\"object\",\"properties\":{\"min\":{\"type\":\"number\"},\"max\":{\"type\":\"number\"}},\"required\":[\"min\",\"max\"]}"),
	"GlucoseImpact":                     json.RawMessage("{\"type\":\"string\",\"enum\":[\"low\",\"medium\",\"high\"]}"),
	"GlucosePrediction":                 json.RawMessage("{\"type\":\"object\",\"properties\":{\"prediction\":{\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/GlucosePredictionPoint\"}},\"impact_score\":{\"$ref\":\"#/components/schemas/GlucoseImpact\"},\"chart\":{\"$ref\":\"#/components/schemas/GlucoseChart\"}},\"required\":[\"prediction\",\"impact_score\",\"chart\"]}"),
	"GlucosePredictionPoint":            json.RawMessage("{\"type\":\"object\",\"properties\":{\"minutes\":{\"type\":\"number\"},\"value\":{\"type\":\"number\"}},\"required\":[\"minutes\",\"value\"]}"),
	"GlucosePredictionProfile":          json.RawMessage("{\"type\":\"object\",\"properties\":{\"age\":{\"type\":\"number\"},\"sex\":{\"$ref\":\"#/components/schemas/Sex\"},\"height\":{\"$ref\":\"#/components/schemas/Height\"},\"weight\":{\"$ref\":\"#/components/schemas/Weight\"},\"activity_level\":{\"$ref\":\"#/components/schemas/ActivityLevel\"},\"health_conditions\":{\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/MedicalCondition\"}}},\"required\":[\"age\",\"sex\",\"height\",\"weight\"]}"),
	"Height":                            json.RawMessage("{\"type\":\"object\",\"properties\":{\"value\":{\"type\":\"number\"},\"unit\":{\"$ref\":\"#/components/schemas/HeightUnit\"}},\"required\":[\"value\",\"unit\"]}"),
	"HeightUnit":                        json.RawMessage("{\"type\":\"string\",\"enum\":[\"in\",\"cm\"]}"),
	"ListFoodLogsResponse":              json.RawMessage("{\"type\":\"object\",\"properties\":{\"total_count\":{\"type\":\"number\"},\"items\":{\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/FoodLog\"}}},\"required\":[\"total_count\",\"items\"]}"),
	"LoggedFood":                        json.RawMessage("{\"type\":\"object\",\"properties\":{\"id\":{\"$ref\":\"#/components/schemas/FoodId\"},\"name\":{\"type\":\"string\"},\"brand_name\":{\"type\":\"string\",\"nullable\":true},\"image_url\":{\"type\":\"string\",\"nullable\":true},\"glycemic_index\":{\"type\":\"number\",\"nullable\":true},\"glycemic_load\":{\"type\":\"number\",\"nullable\":true},\"nutrients\":{\"allOf\":[{\"$ref\":\"#/components/schemas/NutritionFacts\"}]},\"consumed_serving\":{\"allOf\":[{\"$ref\":\"#/components/schemas/FoodLogInputServing\"}]},\"serving_details\":{\"allOf\":[{\"$ref\":\"#/components/schemas/ServingDetails\"}]}},\"required\":[\"id\",\"name\",\"nutrients\",\"consumed_serving\",\"serving_details\"]}"),
	"MedicalCondition":                  json.RawMessage("{\"type\":\"string\",\"enum\":[\"type_2_diabetes\",\"prediabetes\"]}"),
	"NutrientAmount":                    json.RawMessage("{\"type\":\"object\",\"properties\":{\"value\":{\"type\":\"number\"},\"unit\":{\"type\":\"string\"}},\"required\":[\"value\",\"unit\"]}"),
	"NutritionFacts":                    json.RawMessage("{\"type\":\"object\",\"properties\":{\"calories\":{\"$ref\":\"#/components/schemas/NutrientAmount\"},\"protein\":{\"$ref\":\"#/components/schemas/NutrientAmount\"},\"carbohydrates\":{\"$ref\":\"#/components/schemas/NutrientAmount\"},\"net_carbohydrates\":{\"$ref\":\"#/components/schemas/NutrientAmount\"},\"total_fat\":{\"$ref\":\"#/components/schemas/NutrientAmount\"},\"trans_fat\":{\"$ref\":\"#/components/schemas/NutrientAmount\"},\"saturated_fat\":{\"$ref\":\"#/components/schemas/NutrientAmount\"},\"fiber\":{\"$ref\":\"#/components/schemas/NutrientAmount\"},\"total_sugars\":{\"$ref\":\"#/components/schemas/NutrientAmount\"},\"added_sugars\":{\"$ref\":\"#/components/schemas/NutrientAmount\"},\"cholesterol\":{\"$ref\":\"#/components/schemas/NutrientAmount\"},\"calcium\":{\"$ref\":\"#/components/schemas/NutrientAmount\"},\"iron\":{\"allOf\":[{\"$ref\":\"#/components/schemas/NutrientAmount\"}]},\"potassium\":{\"$ref\":\"#/components/schemas/NutrientAmount\"},\"sodium\":{\"$ref\":\"#/components/schemas/NutrientAmount\"},\"vitamin_d\":{\"allOf\":[{\"$ref\":\"#/components/schemas/NutrientAmount\"}]}}}"),
	"PartnerUserId":                     json.RawMessage("{\"type\":\"string\",\"format\":\"opaque\",\"minLength\":1}"),
	"PredictGlucoseBody":                json.RawMessage("{\"type\":\"object\",\"properties\":{\"user_profile\":{\"$ref\":\"#/components/schemas/GlucosePredictionProfile\"},\"foods\":{\"maxItems\":100,\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/FoodLogInputFood\"}},\"start_time\":{\"type\":\"string\",\"format\":\"date-time\"},\"cgm_data\":{\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/CgmReading\"}},\"consumed_foods\":{\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/ConsumedHistoricalFood\"}}},\"required\":[\"user_profile\",\"foods\",\"start_time\"]}"),
	"Restaurant":                        json.RawMessage("{\"type\":\"object\",\"properties\":{\"type\":{\"type\":\"string\",\"enum\":[\"restaurant\",\"menu_item\"]},\"id\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"is_chain\":{\"type\":\"boolean\"},\"distance\":{\"type\":\"number\"},\"city\":{\"type\":\"string\"},\"address1\":{\"type\":\"string\"},\"address2\":{\"type\":\"string\"}},\"required\":[\"type\",\"id\",\"name\"]}"),
	"RestaurantMenuItem":                json.RawMessage("{\"type\":\"object\",\"properties\":{\"type\":{\"type\":\"string\"},\"id\":{\"$ref\":\"#/components/schemas/RestaurantMenuItemId\"},\"name\":{\"type\":\"string\"},\"restaurant_name\":{\"type\":\"string\"},\"is_chain\":{\"type\":\"boolean\"},\"nutrients\":{\"allOf\":[{\"$ref\":\"#/components/schemas/NutritionFacts\"}]},\"glycemic_index\":{\"type\":\"number\"},\"glycemic_load\":{\"type\":\"number\"},\"image_url\":{\"type\":\"string\"},\"distance\":{\"type\":\"number\"},\"servings\":{\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/ServingOption\"}}},\"required\":[\"type\",\"id\",\"name\",\"restaurant_name\",\"servings\"]}"),
	"RestaurantMenuItemId":              json.RawMessage("{\"type\":\"string\",\"format\":\"opaque\",\"minLength\":1}"),
	"ScanFoodPhotoBody":                 json.RawMessage("{\"type\":\"object\",\"properties\":{\"image\":{\"type\":\"string\"}},\"required\":[\"image\"]}"),
	"SearchFoodsByNaturalLanguageBody":  json.RawMessage("{\"type\":\"object\",\"properties\":{\"text\":{\"type\":\"string\",\"maxLength\":512}},\"required\":[\"text\"]}"),
	"SearchRestaurantMenuItemsResponse": json.RawMessage("{\"type\":\"object\",\"properties\":{\"total_count\":{\"type\":\"number\"},\"items\":{\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/RestaurantMenuItem\"}}},\"required\":[\"total_count\",\"items\"]}"),
	"SearchRestaurantsResponse":         json.RawMessage("{\"type\":\"object\",\"properties\":{\"total_count\":{\"type\":\"number\"},\"items\":{\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/Restaurant\"}}},\"required\":[\"total_count\",\"items\"]}"),
	"ServingDetails":                    json.RawMessage("{\"type\":\"object\",\"properties\":{\"id\":{\"$ref\":\"#/components/schemas/ServingId\"},\"quantity\":{\"type\":\"number\"},\"unit\":{\"type\":\"string\"},\"weight_grams\":{\"type\":\"number\",\"nullable\":true}},\"required\":[\"id\",\"quantity\",\"unit\"]}"),
	"ServingId":                         json.RawMessage("{\"type\":\"integer\",\"format\":\"int64\",\"minimum\":0,\"maximum\":9007199254740991}"),
	"ServingOption":                     json.RawMessage("{\"type\":\"object\",\"properties\":{\"id\":{\"$ref\":\"#/components/schemas/ServingId\"},\"quantity\":{\"type\":\"number\"},\"unit\":{\"type\":\"string\"},\"scaling_factor\":{\"type\":\"number\"},\"weight_grams\":{\"type\":\"number\",\"nullable\":true},\"is_primary\":{\"type\":\"boolean\"}},\"required\":[\"id\",\"quantity\",\"unit\",\"scaling_factor\",\"weight_grams\",\"is_primary\"]}"),
	"Sex":                               json.RawMessage("{\"type\":\"string\",\"enum\":[\"male\",\"female\"]}"),
	"SuggestFoodAlternativesBody":       json.RawMessage("{\"type\":\"object\",\"properties\":{\"diet_restrictions\":{\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/DietRestriction\"},\"minItems\":1},\"diet_preferences\":{\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/DietPreference\"},\"minItems\":1}}}"),
	"SuggestFoodAlternativesResponse":   json.RawMessage("{\"type\":\"object\",\"properties\":{\"alternatives\":{\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/FoodAlternative\"}}},\"required\":[\"alternatives\"]}"),
	"UpdateFoodLogBody":                 json.RawMessage("{\"type\":\"object\",\"properties\":{\"foods\":{\"maxItems\":100,\"type\":\"array\",\"items\":{\"$ref\":\"#/components/schemas/FoodLogInputFood\"}},\"timestamp_utc\":{\"type\":\"string\"},\"name\":{\"type\":\"string\",\"maxLength\":256}}}"),
	"Weight":                            json.RawMessage("{\"type\":\"object\",\"properties\":{\"value\":{\"type\":\"number\"},\"unit\":{\"$ref\":\"#/components/schemas/WeightUnit\"}},\"required\":[\"value\",\"unit\"]}"),
	"WeightUnit":                        json.RawMessage("{\"type\":\"string\",\"enum\":[\"lb\",\"kg\"]}"),
}

func (c *Client) mintLegacy(ctx context.Context, input CreateClientTokenInput, pathOverride string) (ClientToken, error) {
	request := MintClientTokenRequest{EndUserID: strings.TrimSpace(input.EndUserID)}
	if input.Scopes != nil {
		request.Scopes = Value(input.Scopes)
	}
	if input.TTLSeconds != nil {
		request.TTLSeconds = Value(float64(*input.TTLSeconds))
	}
	op := opMintClientToken
	if pathOverride != "" {
		op.Path = pathOverride
	}
	var token ClientTokenResponseDto
	response, err := execute(ctx, service{transport: c.transport}, op, request, &token)
	if err != nil {
		if te, ok := err.(*TransportError); ok && te.Kind == "invalid JSON response" {
			return ClientToken{}, &APIError{StatusCode: 502, Message: "Invalid token response", Response: response}
		}
		return ClientToken{}, err
	}
	if token.Token == "" || token.ExpiresIn <= 0 || math.Trunc(token.ExpiresIn) != token.ExpiresIn {
		return ClientToken{}, &APIError{StatusCode: 502, Message: "Invalid token response", Response: response}
	}
	return ClientToken{Token: token.Token, AccessToken: token.Token, TokenType: "Bearer", ExpiresIn: int(token.ExpiresIn), ExpiresAt: token.ExpiresAt}, nil
}
