// Code generated by partner-api-contract/tools/server-sdk/go.mjs. DO NOT EDIT.
package january

import (
	"context"
	"encoding/json"
	"fmt"
)

func invokeFixture(c *Client, id string, raw []byte) (any, *Response, error) {
	switch id {
	case "createClientToken":
		var input CreateClientTokenRequest
		if err := json.Unmarshal(raw, &input); err != nil {
			return nil, nil, err
		}
		return c.CreateClientToken(context.Background(), input)
	case "revokeClientTokens":
		var input RevokeClientTokensRequest
		if err := json.Unmarshal(raw, &input); err != nil {
			return nil, nil, err
		}
		return c.RevokeClientTokens(context.Background(), input)
	case "getCredits":
		var input GetCreditsRequest
		if err := json.Unmarshal(raw, &input); err != nil {
			return nil, nil, err
		}
		return c.GetCredits(context.Background(), input)
	case "searchFoods":
		var input SearchFoodsRequest
		if err := json.Unmarshal(raw, &input); err != nil {
			return nil, nil, err
		}
		return c.Foods.Search(context.Background(), input)
	case "autocompleteFoods":
		var input AutocompleteFoodsRequest
		if err := json.Unmarshal(raw, &input); err != nil {
			return nil, nil, err
		}
		return c.Foods.Autocomplete(context.Background(), input)
	case "suggestFoodAlternatives":
		var input SuggestFoodAlternativesRequest
		if err := json.Unmarshal(raw, &input); err != nil {
			return nil, nil, err
		}
		return c.Foods.SuggestAlternatives(context.Background(), input)
	case "lookupFoodByBarcode":
		var input LookupFoodByBarcodeRequest
		if err := json.Unmarshal(raw, &input); err != nil {
			return nil, nil, err
		}
		return c.Foods.LookupBarcode(context.Background(), input)
	case "getFood":
		var input GetFoodRequest
		if err := json.Unmarshal(raw, &input); err != nil {
			return nil, nil, err
		}
		return c.Foods.Get(context.Background(), input)
	case "searchRestaurants":
		var input SearchRestaurantsRequest
		if err := json.Unmarshal(raw, &input); err != nil {
			return nil, nil, err
		}
		return c.Restaurants.Search(context.Background(), input)
	case "getRestaurantMenuItems":
		var input GetRestaurantMenuItemsRequest
		if err := json.Unmarshal(raw, &input); err != nil {
			return nil, nil, err
		}
		return c.Restaurants.GetMenuItems(context.Background(), input)
	case "searchRestaurantMenuItems":
		var input SearchRestaurantMenuItemsRequest
		if err := json.Unmarshal(raw, &input); err != nil {
			return nil, nil, err
		}
		return c.Restaurants.SearchMenuItems(context.Background(), input)
	case "scanFoodPhoto":
		var input ScanFoodPhotoRequest
		if err := json.Unmarshal(raw, &input); err != nil {
			return nil, nil, err
		}
		return c.FoodAnalysis.AnalyzePhoto(context.Background(), input)
	case "searchFoodsByNaturalLanguage":
		var input SearchFoodsByNaturalLanguageRequest
		if err := json.Unmarshal(raw, &input); err != nil {
			return nil, nil, err
		}
		return c.FoodAnalysis.AnalyzeDescription(context.Background(), input)
	case "correctPhotoScan":
		var input CorrectPhotoScanRequest
		if err := json.Unmarshal(raw, &input); err != nil {
			return nil, nil, err
		}
		return c.FoodAnalysis.Correct(context.Background(), input)
	case "createFoodLog":
		var input CreateFoodLogRequest
		if err := json.Unmarshal(raw, &input); err != nil {
			return nil, nil, err
		}
		return c.FoodLogs.Create(context.Background(), input)
	case "listFoodLogs":
		var input ListFoodLogsRequest
		if err := json.Unmarshal(raw, &input); err != nil {
			return nil, nil, err
		}
		return c.FoodLogs.List(context.Background(), input)
	case "getFoodLog":
		var input GetFoodLogRequest
		if err := json.Unmarshal(raw, &input); err != nil {
			return nil, nil, err
		}
		return c.FoodLogs.Get(context.Background(), input)
	case "updateFoodLog":
		var input UpdateFoodLogRequest
		if err := json.Unmarshal(raw, &input); err != nil {
			return nil, nil, err
		}
		return c.FoodLogs.Update(context.Background(), input)
	case "deleteFoodLog":
		var input DeleteFoodLogRequest
		if err := json.Unmarshal(raw, &input); err != nil {
			return nil, nil, err
		}
		response, err := c.FoodLogs.Delete(context.Background(), input)
		return nil, response, err
	case "predictGlucose":
		var input PredictGlucoseRequest
		if err := json.Unmarshal(raw, &input); err != nil {
			return nil, nil, err
		}
		return c.Glucose.Predict(context.Background(), input)
	}
	return nil, nil, fmt.Errorf("unknown fixture operation")
}
